### ISSUE TITLE
Doesn't work in yarn workspaces

### ISSUE THREAD

**Issue by PaulRBerg** [rkalis/truffle-plugin-verify#10]
Yarn workspaces is this new way of intelligently managing your npm modules in a monorepo by installing them only once (or multiple times if there are overlapping versions). What it does is that it aggregates all the modules at the root of your project.

If I install truffle-plugin-verify in [the "contracts" package of this monorepo](https://github.com/SablierApp/sablier/tree/master/packages/contracts) and I try to run it, I get the following error:

> Error: truffle-plugin-verify listed as a plugin, but not found in global or local node modules!

Of course, I moved on and installed the module globally, but I can't use this plugin on CI.

**Comment by rkalis** [comment]
Good workaround to install globally for now I guess, but it's preferable to include it in the local project. 

This sounds like it affects all Truffle plugins, so I think this issue should be added to the Truffle repo instead, so it can be tracked there. What do you think @gnidan?

**Comment by gnidan** [comment]
Oh yes please! Looks like this repo is the Truffle plugin issues home away from home :)

I'll make the trufflesuite/truffle issue tomorrow if no one beats me to it.

**Comment by PaulRBerg** [comment]
Thanks guys!

**Comment by rkalis** [comment]
I opened an [issue on trufflesuite/truffle](https://github.com/trufflesuite/truffle/issues/2409) for this. Closing it here.
