### ISSUE TITLE
Support for Fantom Testnet

### ISSUE THREAD

**Issue by light-fury** [rkalis/truffle-plugin-verify#100]
First, I want to say Thank you for the team of this library.
It makes our life easier.

Btw, I saw that it is supporting fantom mainnet with ftmscan.com.
Could you please add a support for testnet.ftmscan.com? It is for network_id: 4002
And it is from the same company who built etherscan, ftmscan and bscscan.

**Comment by rkalis** [comment]
Thanks, I missed this issue before. FTM testnet support has now been released in v0.5.12
