### ISSUE TITLE
hi, where do you get the polygonscan api from?

### ISSUE THREAD

**Issue by aster2709** [rkalis/truffle-plugin-verify#102]
unlike etherscan where it shows a button to sign up and obtain the api_key, i have deployed my contract to mumbai testnet, and looking to verify it with your plugin, but i cant find where to obtain the api key from like etherscan, can you tell me

**Comment by rkalis** [comment]
Hey, to sign in and get an API key you need to be on the "mainnet" version of PolygonScan. Then you can use the same API key for Polygonscan mainnet and testnet. Good luck!
