### ISSUE TITLE
No instance of contract [contractname] found for network id 1

### ISSUE THREAD

**Issue by TheHumanoids** [rkalis/truffle-plugin-verify#103]
I've deployed a contract on the mainnet and am trying to verify it but I keep getting this message when using the following command:

`truffle run verify [contractname] --network mainnet`

`
No instance of contract [contractname] found for network id 1
Failed to verify 1 contract(s): [contractname]
`

Am I missing something?

**Comment by rkalis** [comment]
Did you deploy the contract with `truffle migrate ... --network mainnet`? Was the contract deployed directly from the truffle migrations interface (`deployer.deploy(...)`) or was it deployed by another contract?

**Comment by ClubMylo** [comment]
I have this same issue. I deployed with truffle.

**Comment by rkalis** [comment]
Was the contract deployed directly from the truffle migrations interface (`deployer.deploy(...)`) or was it deployed by another contract? Do you have a code repo I can look at or do you have any other information about your project?

**Comment by ClubMylo** [comment]
Can I email you directly all the information?

**Comment by rkalis** [comment]
Sure, you can send it to roscokalis@gmail.com 👍

**Comment by rkalis** [comment]
@ClubMylo was able to figure out their issue. I haven't heard from @TheHumanoids, so I'm closing this issue. Feel free to re-open with more information in the future.
