### ISSUE TITLE
"Checking status of verification request xxxx" forever, stuck there.

### ISSUE THREAD

**Issue by d-sfounis** [rkalis/truffle-plugin-verify#109]
Hey guys,

Started experiencing this today after migrating my truffle contract to the BSC testnet.
I run `truffle run verify myContract --debug --network bsc_testnet` and it just gets stuck on "Checking status of verification request xxx".

The `xxx` hash will change every time I `CTRL-C` and run a new verification attempt.

Hadn't experience any problems with `truffle-plugin-verify` before that and it's one of my favourite little tools.

**Comment by xiskoct** [comment]
the same for me

**Comment by d-sfounis** [comment]
> the same for me

Let's wait until tomorrow before we nag the repo owner, might be some temporary failure or BSC/BSCscan

**Comment by jcihocki** [comment]
Just noting here that uploading the json output from --debug directly to the etherscan web app to verify still works as a stopgap

**Comment by xiskoct** [comment]
is all the output of the --debug uploaded? or just from the sourcecode attribute? I am trying to verify it through the json in bscscan's testnet but I get:

Unable to process the standard-input-json you uploaded. ErrCode: Unable to parse Json file

**Comment by d-sfounis** [comment]
> Just noting here that uploading the json output from --debug directly to the etherscan web app to verify still works as a stopgap

Does bscscan have an equivalent? Could I please ask you for a link?

**Comment by xiskoct** [comment]
I only tested it from https://testnet.bscscan.com/

**Comment by EliteDaMyth** [comment]
Problem still persists!

**Comment by nnamss** [comment]
Works on testnet bscscan but the issue still persists on mainnet.

**Comment by rkalis** [comment]
Hey, since so many people are suddenly experiencing this, I do assume that there's some downtime on the Etherscan/BscScan side that causes it. @Enigmatic331 do you know if there's any issues with the verification API right now?

**Comment by degeneratemoney** [comment]
Thanks, haven't been able to verify anything on Rinkeby the entire day

**Comment by jsdu** [comment]
been having this issue all day today too

**Comment by Enigmatic331** [comment]
Hey everyone - This should be sorted now - Please do give it another shot if your contracts are not verified yet, and let us know if there are issues?

Thanks and sorry for the trouble!

**Comment by d-sfounis** [comment]
> Hey everyone - This should be sorted now - Please do give it another shot if your contracts are not verified yet, and let us know if there are issues?
> 
> Thanks and sorry for the trouble!

What was the issue?

**Comment by rkalis** [comment]
Thanks for resolving the issues @Enigmatic331!
