### ISSUE TITLE
Cannot find module '@openzeppelin/contracts/GSN/Context.sol'

### ISSUE THREAD

**Issue by sudojanuc** [rkalis/truffle-plugin-verify#111]
Hello, 
whenever i try to verify my ERC721 Contract I get the error message:
"Cannot find module '@openzeppelin/contracts/GSN/Context.sol'".

I am using the openzeppelin library (installed via npm install).

My SmartContract starts like this:

```
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/ownership/Ownable.sol";

contract ChallengeManager is LockFactory, ERC721, Ownable {
...
```

The ERC721 Contract has a dependency to the requested "Context.sol" Contract.

I also tried to import "@openzeppelin/contracts/GSN/Context.sol" on my ChallengeManager Contract, but i still get the same Error.

**Comment by d-sfounis** [comment]
I think `Ownable` is under `import "@openzeppelin/contracts/access/Ownable.sol";`.

**Comment by sudojanuc** [comment]
Thanks for the reply. The issue is definitely coming from the ERC721 import. I already removed the Ownable part and still got the same fault. 
But I can verify it if i remove the ERC721 import.

By the way, I forgot to mention that im using version "2.5.1" of the openzeppelin library. Maybe this explains the difference in the import. I have to use this version, because I am using another library which is wirtten in solidity version 5.17.

**Comment by rkalis** [comment]
Do you have your code repository available somewhere to check out what might be the issue? Also what OS are you using?

**Comment by sudojanuc** [comment]
Yes, thats the contract I'm trying to verify:
https://github.com/sudojanuc/fitness-challenge/blob/main/contracts/ChallengeManager.sol

Contract address: 
0x4D70519d63158e7be67c1B9B01C4b126039805FB

I am using Windows 10, but i also failed on Linux.

**Comment by daweizhao23** [comment]
I might run into a similar issue.
"Cannot find module '@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol'"
I am using @openzeppelin/contracts-upgradeable@3.4.0

**Comment by werksone** [comment]
Did anyone sort this issue out I seem to be running into a very similar issue "Cannot find module '@openzeppelin/"

**Comment by werksone** [comment]
`truffle run verify NewTest --network rinkeby --debug                                                    [13:06:18]
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.15
Verifying NewTest
Reading artifact file at /Users/werksone/Documents/NFT/NFTTest04Truffle/build/contracts/NewTest.json
Retrieving constructor parameters from https://api-rinkeby.etherscan.io/api?apiKey=FCCUFVZVZCN462K616Q6WCVJI4FNRMMTEX&module=account&action=txlist&address=0x5a1a3b04e98Cb8845cc4ADe0274FA7A991F6000f&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e7777772e6675636b79612e636f6d000000000000000000000000000000000000
Cannot find module '@openzeppelin/contracts/utils/introspection/IERC165.sol'
Require stack:
- /usr/local/lib/node_modules/truffle-plugin-verify/verify.js
- /usr/local/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/local/lib/node_modules/truffle/build/cli.bundled.js
Failed to verify 1 contract(s): NewTest`

**Comment by eulerbeat** [comment]
Same issue here - https://github.com/rkalis/truffle-plugin-verify/issues/117

Not resolved yet

**Comment by rkalis** [comment]
To anyone experiencing this issue: what version of Node are you running?

**Comment by romuloags** [comment]
same issue, I can not verify the contracts where I used the openzeppelin library (Context.sol)

**Comment by romuloags** [comment]
I'm using v14.17.5 (node.)

**Comment by rkalis** [comment]
Any reproduction repos?

**Comment by romuloags** [comment]
sure. https://github.com/romuloags/redCriptoPay/tree/testnet 
I deployed my contracts on ropsten , I have only been able to verify 1 contract (the one doesn't have openzeppelin library)

**Comment by rkalis** [comment]
Thanks for providing the repo. When I ran `npm install` and tried to verify I got some other error messages which were resolved after upgrading from `0.5.3` to `0.5.20`.

From there I have tried to reproduce this issue with a lot of different configurations (any combination of using Node 12/14 and NPM 6/7/8/Yarn), but I wasn't able to reproduce it.

@romuloags what OS and Truffle version are you running? And is there anything else that you can think of that might be relevant?

**Comment by romuloags** [comment]
I'm using WSL2 
Ubuntu 20.04.2 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)
 npm: '6.14.14',
Truffle v5.4.7 (core: 5.4.7)
Solidity v0.5.16 (solc-js)
Node v14.17.5
Web3.js v1.5.2

**Comment by rkalis** [comment]
Could you just try updating to the latest Truffle (`npm install -g truffle@latest`) and retry the process? That's the only thing that I can think of atm.

**Comment by romuloags** [comment]
It did not work.

**Comment by romuloags** [comment]
I  decided to copy and paste OpenZeppelin libraries directly in the contracts, and it worked just fine. even though you have to do this and can be kind of annoying, this plugin really helps to verify the contracts faster and easier than directly from etherscan. thanks for the help though.

**Comment by hasandogu** [comment]
I have the same issue but with a package that is local (bootstrapped with lerna) instead of OpenZeppelin.

npm: 7.17.0
node: 14.15.1
truffle: 5.4.26
truffle-plugin-verify: 0.5.20
solidity: 0.8.6

**Comment by nicknovoa03** [comment]
Been dealing with the same issue, seems like you have to have the truffle-config.js and package.json in the same directory, for example, mine is within the src directory for my project. This is bad practice but works with no errors. Also, truffle-plugin-verify does not work for the rinkeby test net from what I can tell.

**Comment by rkalis** [comment]
@nicknovoa03 do you have a repo with the config where it doesn't work for you that I can look at?

**Comment by script-money** [comment]
`cp -r node_modules/@openzeppelin contracts` then run verify works for me

**Comment by rkalis** [comment]
That's interesting @script-money, do you have a repo where I can reproduce this issue?

**Comment by script-money** [comment]
> That's interesting @script-money, do you have a repo where I can reproduce this issue?

https://github.com/script-money/blockchain-developer-bootcamp-final-project

**Comment by rkalis** [comment]
I can't reproduce the issue on that repository. People with this issue, please provide your OS, Truffle version, Node version, and NPM/Yarn version in the comments to figure out common things between the people with these issues.

**Comment by script-money** [comment]
> `cp -r node_modules/@openzeppelin contracts` then run verify works for me

macOS big Sur 11.6
Truffle v5.4.15 (core: 5.4.15)
Node v14.17.6
yarn version v1.22.10

**Comment by rkalis** [comment]
😅 so it looks like we have people experiencing this issue with Windows/Mac/Linux, both with Yarn and NPM, so it doesn't look like there's anything you guys have in common . But at the same time the *majority* of people (including myself) don't have this issue. I'm stumped.

**Comment by hirokimoto** [comment]
It has been deprecated in the latest version.
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2520

**Comment by dherbst** [comment]
I ran into this issue as well, `truffle compile` worked ok, and `migrate` worked as well.  But when I tried `test` the openzeppelin artifact files couldn't be found by the resolver.

I noticed the openzeppelin contracts were not listed in the compilation logs for `test`

Then I did `truffle test --compile-all` and that fixed it.   Subsequent runs of `truffle test` without the `--compile-all` flag work as well now.   

Dropping this here in hopes this helps someone get past this quicker than I did.

**Comment by Fabbiya** [comment]
This issue happens when you want to use an older version of SDKs with a newer version and mixing all. To prevent this to happen, try using the same version or updating SDK versions from node_modules. 
This always works and it's better to use the latest version :)

**Comment by hasandogu** [comment]
I have everything as the latest and still see this issue. I will try and repro this with a smaller repo wwhere packages are also managed by lerna, as it seems to be related with symlinks in packages.

**Comment by hasandogu** [comment]
@rkalis I have a simple repo for you. The repro steps are in the README.

https://github.com/hasandogu/lerna-contracts-test/

**Comment by hasandogu** [comment]
I have some more info. If I use a local version of `truffle-plugin-verify` using `yalc` the verification works without a hiccup.

**Comment by emilyJLin95** [comment]
@rkalis bump - I'm receiving a similar error, except the import 
@hasandogu did you figure it out?

Versions
```
Truffle v5.5.28 (core: 5.5.28)
Ganache v7.4.0
Solidity v0.5.16 (solc-js)
Node v16.17.0
Web3.js v1.7.4
truffle-plugin-verify 0.5.28
MacOS: Monterey v12.2.1
```

Trying to verify the RentablePets contract (https://github.com/trufflesuite/unleashed_rentable_nft)
```
truffle run verify RentablePets --network dashboard --debug
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.28
Retrieving network's network ID & chain ID
Verifying RentablePets
Reading artifact file at /Users/emilylin/dev/unleashed_rentable_nft/build/contracts/RentablePets.json
Retrieving constructor parameters from https://api-goerli.etherscan.io/api?apiKey=G4NA25PVEA8T3VXZ7EUU7ZU437R1ARQCH1&module=account&action=txlist&address=0x1425893296d3C7294BE14E6D0C62d84587d94a08&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x
Cannot find module '@openzeppelin/contracts/utils/introspection/IERC165.sol'
Require stack:
- /Users/emilylin/.nvm/versions/node/v16.17.0/lib/node_modules/truffle-plugin-verify/verify.js
- /Users/emilylin/.nvm/versions/node/v16.17.0/lib/node_modules/truffle/node_modules/original-require/index.js
- /Users/emilylin/.nvm/versions/node/v16.17.0/lib/node_modules/truffle/build/cli.bundled.js
Failed to verify 1 contract(s): RentablePets
```

**Comment by hasandogu** [comment]
I used a local version of the plugin with `yalc`. That resolved my issue
but I can't run stock plugin.

**Comment by emilyJLin95** [comment]
@hasandogu hmm I'm not sure if I'm using `yalc` correctly

Is it

1. Navigate to `truffle-plugin-verify` folder (`/Users/emilylin/.nvm/versions/node/v16.17.0/lib/node_modules/truffle-plugin-verify/`)
2. `yalc publish`
3. Navigate back to `rentable-nft` directory
4. `yalc add truffle-plugin-verify`

It's not getting added to my `package.json` dependencies, so I think I'm using `yalc` incorrectly

**Comment by emilyJLin95** [comment]
Well, I just followed @script-money 's suggestion and copied all the files into the contracts directory

I wonder if there's a way that we don't have to do that and verify will recognize files that live in node_modules?

**Comment by hasandogu** [comment]
> 

Actually, I cloned the plugin from its Github.

1. git clone https://github.com/rkalis/truffle-plugin-verify.git
2. Navigate to this folder and call `yalc publish`

The rest of the steps are the same. It won't get added to package.json but rather yarn.lock.

**Comment by rkalis** [comment]
> @rkalis I have a simple repo for you. The repro steps are in the README.

Thank you for taking the time to put that together. Unfortunately, I cannot reproduce the issue. When following the instructions on your repo, the contract successfully verifies (had to change Rinkeby to Goerli though because Rinkeby is deprecated). See https://goerli.etherscan.io/address/0x34bD0B8b2aC37Bd74A98a03e17D224D46E0eeA3c#code and https://goerli.etherscan.io/address/0xaea88fe19c42673cef55c6ccf1631cfb329966d1#code.

**Comment by rkalis** [comment]
Ok I think I've finally been able to track down this issue. When installing truffle-plugin-verify as a *global* NPM dependency, we run into these issues. When installing it *locally* there are no issues. Since most people (including myself) install truffle plugins locally, this was hard to reproduce without that specific point of information.

This issue should now be fixed in version 0.5.30 of the plugin. Will rename and close the issue. Feel free to re-open if the issue persists.

**Comment by Hashflower** [comment]
To anyone having the same issue thats how I solved it : 

sudo rm -rf /usr/local/lib/node_modules/truffle-plugin-verify
npm install truffle-plugin-verify --save-dev

Worked

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @werksone)
