### ISSUE TITLE
Is that possible to verify all contracts at once?

### ISSUE THREAD

**Issue by lawweiliang** [rkalis/truffle-plugin-verify#114]
Current if I have 30 solidity contracts, I need to key in one by one

Currently
`truffle run verify ContractA --network rinkeby`
`truffle run verify ContractB --network rinkeby`
`truffle run verify ContractC --network rinkeby`

Is that any I could run something like that, then it will eventually verify all my contracts?
`truffle run verify all --network rinkeby`

thanks buddies

**Comment by rkalis** [comment]
Seems like a fair feature to have. I think it should be possible to add an `--all` flag. Then the plugin should open every artifact in the contracts build folder and check if they have a deployed address for the specified network, if they do, it should get verified. `--all` should fail if used together with `--forceConstructorArgs`.

I'll need to find the time to implement this at some point in the future. I'll also accept PRs that add the functionality.

In the mean time, you can also write the different contracts in a single command, which is not as easy as saying "all", but it's easier than using new commands for every contract

```
truffle run verify ContractA ContractB ContractC --network rinkeby
```

**Comment by rkalis** [comment]
Since Truffle is being sunset, I don't plan to add new features, so I'm closing this issue.

**Comment by lawweiliang** [comment]
@rkalis Agree. Now I also don't use truffles anymore. 😄 

Anyway, appreciate your effort.  Cheers.
