### ISSUE TITLE
Verify contracts that were deployed/instantiated internally (using new) by a contract's constructor

### ISSUE THREAD

**Issue by d-sfounis** [rkalis/truffle-plugin-verify#116]
Hai,

Is it possible to do what the title says thourgh `truffle-plugin-verify`?

I've got something like this in a single file:

```solidity
contract myContract1 {
    constructor(address addr) {}
}

contract myContract2 {
     myContract1 foo;
     constructor(address addr){
         foo = new myContract1(addr);
     }
}
```

You can imagine myContract2 is the *main* contract. I verify it just fine using the plugin, but the internal contract remains unverified. I've also tried running `truffle run verify` on it, but it of course cannot find a deployment instance.

**Comment by rkalis** [comment]
Unfortunately, this doesn't work automatically, since we can't automatically get the constructor arguments for these kinds of contracts (see #8).

If you know the constructor arguments that were used in the deployment you can use the `--forceConstructorArgs` flag, e.g.:

```
truffle run verify MetaCoin --forceConstructorArgs string:0000000000000000000000000cb966d6a7702a4eff64009502653e302b3ec365 --network goerli
```

**Comment by rkalis** [comment]
I'll add though that it might be possible to automatically figure out the constructor args for these "factory-deployed" contracts by using Tenderly or something similar, but I haven't figured that out yet. So if you (or anyone else) can figure it out I'll buy you a drink at the next devcon!
