### ISSUE TITLE
Snowtrace(Avalanche Fuji Explorer) support

### ISSUE THREAD

**Issue by Julian-dev28** [rkalis/truffle-plugin-verify#124]
Hello

I tried to verify contracts on the Fuji Network but was unsuccessful due to an error, "No Etherscan API key specified" and then "Invalid API Key"

This is because of a bug found in network configurations within truffle-plugin-verify regarding Avalanche networks, `./node_modules/truffle-plugin-verify/constants.js`

Etherscan usually has the integer '1' assigned to it but when deploying to Avalanche Fuji(network ID 43113) we connect to its 1st subnet which is also Identified as '1'

This leads truffle-verify to believe that we are attempting to verify a contract on Ethereum's  mainnet which results in the "invalid api key" Error

To correct the routing to Avalanche's Fuji network and snowtrace, you must navigate to:

`./node_modules/truffle-plugin-verify/constants.js`

and implement the following:

```js
const API_URLS = {
  1: 'https://api-testnet.snowtrace.io/api',
```
  
```js
  const EXPLORER_URLS = {
  1: 'https://testnet.snowtrace.io/address',
```

**Comment by rkalis** [comment]
Oof! Thanks for finding that @Julian-dev28. That leaves us in a bit of a pickle, since we use the truffle config's `network_id` to detect the network, so now we cannot automatically detect whether the network is Avalanche or Ethereum Mainnet.

We need to figure out a different way to differentiate between them. Perhaps we'd need to try to talk to the configured provider and retrieve the `chainId` from there and use the chain ID instead of the network ID. I'll have to figure out if that's possible though.

Thanks in any case for raising this issue. I'm open to any suggestions for how to go about this.

**Comment by Julian-dev28** [comment]
No prob. I actually found this bug in July before there was support for Fuji through snowtrace APIs but there wasn't a solution yet because we did not provide API keys to verify contracts at the time.

As far as a solution, I might suggest that someone clone this tool or perhaps truffle develops this tool specifically for the Avalanche network by implementing the suggested changes

Another solution might be to add an If statement somewhere in the logic
ex: `node_modules/truffle-plugin-verify/verify.js`

```
const apiKey = apiUrl.includes('snowtrace') && snowtraceApiKey
            ? snowtraceApiKey
            : etherscanApiKey
}
            
```
perhaps something along the lines of 

```
if (apiUrl.includes('snowtrace'){
let const networkId = 1
}
```

Or perhaps hardcode the config for snowtrace in `./node_modules/truffle-plugin-verify/constants.js` and utilize them in `node_modules/truffle-plugin-verify/verify.js`

Perhaps something similar to 


`./node_modules/truffle-plugin-verify/constants.js`:

```
const SNOWTRACE_EXPLORER_URL = 'https://testnet.snowtrace.io/address'
const SNOWTRACE_API_URL = 'https://api-testnet.snowtrace.io/api'
```
then


`node_modules/truffle-plugin-verify/verify.js`:
 ```
 const parseConfigForSnowtrace = (config) => {
    // Truffle handles network stuff, just need to get network_id
    const networkId = 1
    const apiUrl = SNOWTRACE_API_URL
    const SNOWTRACE_API_URL = SNOWTRACE_API_URL
    enforce(SNOWTRACE_API_URL, `Etherscan has no support for network ${config.network} with id ${networkId}`, logger)

  const snowtraceApiKey = config.api_keys && config.api_keys.snowtrace


  const snowtrace_apiKey = SNOWTRACE_API_URL.includes('snowtrace') && snowtraceApiKey
            ? snowtraceApiKey
            : etherscanApiKey
```

**Comment by rkalis** [comment]
Hey @Julian-dev28, I just published v0.5.18 of the plugin which should fix the issue (tested it locally with Fuji). What I did is talk to the configured provider from the truffle-config and retrieve the chain ID from it, then use that chain ID in the place of network ID to get the API / explorer urls. If no provider is configured or it cannot retrieve the chain ID it falls back on network ID (shouldn't happen).

**Comment by Julian-dev28** [comment]
Awesome thank you!!!

**Comment by webdev0305** [comment]
It was your API Key problem.
I met the same issue, but my partner's working well.
So I tried with his key, It was working well.
You need to try other API key.

**Comment by Monarch717** [comment]
`Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key
`
Is there any alternative solution for verify contract on avalanche?
I am using snowtrace api. 
Please help me
