### ISSUE TITLE
Address override yields "The /"path/" argument must be of type string." error.

### ISSUE THREAD

**Issue by DAC-PhilThomsen** [rkalis/truffle-plugin-verify#125]
I used the tool for quite some time and today was the first time something didn´t work as expected.
I tried to verify a Contract I deployed with Remix by using the optional address override as specified in the Documentation on npm.
I used the override many times before successfully, but today I got an error that I cannot figure out. 
Everything seems to go fine until the error 
"The /"path/" argument must be of type string." 
appears. 
I pasted my console output I got using the --debug flag down below. Can anyone give any insight into this error? Where could it stem from?

```
> truffle run verify ClaimAggregator@0xB8368Cef0B57e210D6508dFB4131F64bD00e0169 --network mainnet --debug
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.15
Verifying ClaimAggregator@0xB8368Cef0B57e210D6508dFB4131F64bD00e0169
Reading artifact file at D:\Dokumente\GitVScode\playaround\build\contracts\ClaimAggregator.json
Custom address 0xB8368Cef0B57e210D6508dFB4131F64bD00e0169 specified
Retrieving constructor parameters from https://api.etherscan.io/api?apiKey=53RPKX34QD9Y8Q2AA83K9ZVG6BFPHYMP5Q&module=account&action=txlist&address=0xB8368Cef0B57e210D6508dFB4131F64bD00e0169&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x
The "path" argument must be of type string. Received undefined
Failed to verify 1 contract(s): ClaimAggregator@0xB8368Cef0B57e210D6508dFB4131F64bD00e0169
```

**Comment by rkalis** [comment]
Can you try updating to the latest version of the plugin (0.5.18) and see if it pursists?

**Comment by DAC-PhilThomsen** [comment]
Fixed. My bad for not checking the latest version. Thanks a lot.

**Comment by rkalis** [comment]
No worries, was fixed very recently. Happy it's not a *new* big haha!
