### ISSUE TITLE
Mumbai Polygon API key Failed to Verify

### ISSUE THREAD

**Issue by shep-analytics** [rkalis/truffle-plugin-verify#129]
With a valid API key from polygon, I always get that the API key is invalid trying to verify on the mumbai testnet. This plugin has saved me countless hours on other chains, I would love to be able to completely use it on MATIC.

Any help would be greatly appreciated!

```
truffle run verify Widget --network mumbai
Verifying Widget
Invalid API Key
Failed to verify 1 contract(s): Widget
```

**Comment by rkalis** [comment]
Did you configure a separate API key for PolygonScan? You need to request a separate API key from PolygonScan to verify on Polygon / Mumbai, you can't use the same API key as with Etherscan.

**Comment by shep-analytics** [comment]
Yes, I used a polygonScan API

Alex

**Comment by rkalis** [comment]
Does this issue still persist?

**Comment by rkalis** [comment]
This may be a duplicate of #97. If this issue persists, please provide any more information in that issue.
