### ISSUE TITLE
Lil problem with deploying contracts with 2,3,4..... digits in Migrations directory

### ISSUE THREAD

**Issue by villarode** [rkalis/truffle-plugin-verify#130]
Hello and sorry to pester again)

In my migrations subdir I created (aside from 1_initial_migration) another file 2_deploy_Villa_Rode_AL.js:

const Villa_Rode_AL = artifacts.require("Villa_Rode_AL");

module.exports = function (deployer) {
  deployer.deploy(Villa_Rode_AL);
};

I am running deployment script $ yarn truffle deploy --network rinkeby

Apparently the 2nd migration to my contract Villa_Rode_AL stalls somehow::

Compiling your contracts...
===========================
> Compiling @openzeppelin\contracts\access\Ownable.sol
> Compiling @openzeppelin\contracts\token\ERC721\ERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721Receiver.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\ERC721Enumerable.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\IERC721Enumerable.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\IERC721Metadata.sol
> Compiling @openzeppelin\contracts\utils\Address.sol
> Compiling @openzeppelin\contracts\utils\Context.sol
> Compiling @openzeppelin\contracts\utils\Strings.sol
> Compiling @openzeppelin\contracts\utils\introspection\ERC165.sol
> Compiling @openzeppelin\contracts\utils\introspection\IERC165.sol
> Compiling @openzeppelin\contracts\utils\math\SafeMath.sol
> Compiling .\contracts\ApprovedSpenderContract.sol
> Compiling .\contracts\ERC721Tradable.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\Villa_Rode_AL_OS721_Rinkeby.sol
> Compiling .\contracts\common\meta-transactions\ContentMixin.sol
> Compiling .\contracts\common\meta-transactions\EIP712Base.sol
> Compiling .\contracts\common\meta-transactions\Initializable.sol
> Compiling .\contracts\common\meta-transactions\NativeMetaTransaction.sol
> Artifacts written to C:\Users\User\OS721_Rinkeby\build\contracts
> Compiled successfully using:
   - solc: 0.8.10+commit.fc410830.Emscripten.clang

Migrations dry-run (simulation)
===============================
> Network name:    'rinkeby-fork'
> Network id:      4
> Block gas limit: 29999774 (0x1c9c29e)

2_deploy_Villa_Rode_AL.js
=========================

   Deploying 'Villa_Rode_AL'
   -------------------------

Error:  *** Deployment Failed ***

"Villa_Rode_AL" -- Invalid number of parameters for "undefined". Got 0 expected 1!.

    at C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:70:1)
    at Migration._load (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:56:1)
    at Migration.run (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:217:1)
    at Object.runMigrations (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.run (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\migrate\index.js:87:1)
    at runMigrations (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:258:1)
    at setupDryRunEnvironmentThenRunMigrations (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:246:1)
    at Object.run (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:215:1)
    at Command.run (C:\Users\User\OS721_Rinkeby\node_modules\truffle\build\webpack:\packages\core\lib\command.js:183:1)
Truffle v5.4.19 (core: 5.4.19)
Node v17.1.0

What would you think might be the problem?)

**Comment by rkalis** [comment]
If your contract has constructor parameters you need to provide a value for them in the `deployer.deploy` call

**Comment by villarode** [comment]
The constuctor in the contract is below, would I then need to put address _proxyRegistryAddress right after Villa_Rode_AL within round brackets in deployer.deploy call?

import "./ERC721Tradable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**

@title Villa_Rode_AL_OS721_Rinkeby

Creature - a contract for my non-fungible creatures.
*/
contract Villa_Rode_AL is ERC721Tradable {
constructor(address _proxyRegistryAddress)
ERC721Tradable("Villa_Rode_AL_OS721_Rinkeby", "OSC", _proxyRegistryAddress)
{}

function baseTokenURI() override public pure returns (string memory) {
return "https://gateway.pinata.cloud/ipfs/QmQ4btGqRKfLwfJgAuh7k3cAqRDQZj1WTV1L8f9EhdunHQ/";
}

function contractURI() public pure returns (string memory) {
return "https://creatures-api.opensea.io/contract/opensea-creatures";
}
}

**Comment by rkalis** [comment]
You need to put the actual registry address. Presumably this code is from some kind of tutorial, so perhaps they can give you more information on how to proceed with the contract / deployment. Since it's going to be difficult for me to help you debug your contracts and deployment process.

**Comment by villarode** [comment]
yes it is actually fromOpenSea tutorial on their site.... I will try to get some info from them... Thank you very much for your help, it is much appreciated!)

**Comment by rkalis** [comment]
Happy to help! Feel free to re-open this issue if you run into any verification issues after you get the deployment working correctly!
