### ISSUE TITLE
Providing my own ContractCode during a verification run

### ISSUE THREAD

**Issue by d-sfounis** [rkalis/truffle-plugin-verify#131]
Hi,

You might be aware that **Arbitrum**'s arbiscan is having trouble (for the past 6 months) with sub-contracts generated through `new` of a parent contract. These addresses are reported as Addresses, not Contracts.

Therefore, any verification request by `truffle-plugin-verify` fail with error code:
`Unable to locate ContractCode at 0x74915bc0716a2a6545fb33cb4414a2d364712efc`

Is there any way for me to provide ContractCode via another source? For example, for the same contract address that I'm interested in, Arbiscan.io reports it as an address (no ContractCode), but Arbitrum's own explorer (explorer.arbitrum.io) correctly reports deployed code.

**Comment by rkalis** [comment]
Oh that's weird! @Enigmatic331, something for you guys to look at?

**Comment by Enigmatic331** [comment]
Ah. That is as we don't have access to the rpc calls which makes it possible for us to index factory creates/internal creates (i.e. CREATE/CREATE2 opcodes)... Yet.

Once these are made available to us we will roll out this feature for Arbiscan! 🙏

**Comment by rkalis** [comment]
Thanks for the quick reply! So @d-sfounis I'll close this issue for now since there's nothing for me to implement here. Once it's implemented in Arbiscan it should work from the plugin side as well!
