### ISSUE TITLE
Does not verify implementation contract when using Upgradeable proxies

### ISSUE THREAD

**Issue by PixelHeroMedia** [rkalis/truffle-plugin-verify#137]
I am deploying an upgradeable proxy, but this plugin only verifies the Proxy contract and not the Implementation one.
If I try to run it, it tells me the Proxy address is already verified, but I need to verify the Implementation too...

any way to do this?

**Comment by rkalis** [comment]
Yes, this is a known issue, and it would be possible to fix this in the plugin, but it would be quite some work. A workaround for now is finding the address for the contract and running `truffle run verify Contract@<address>`. See #80 for more conversation around proxies.
