### ISSUE TITLE
Polygon Mumbai: Failed to verify (Görli AOK).

### ISSUE THREAD

**Issue by timwoodward** [rkalis/truffle-plugin-verify#139]
On standby to assist remotely with issue resolution.

Repeated failures with complex deployment; created simple test contract to fault find: failed to verify on Polygon Mumbai with and without custom address; tested and working AOK on Görli only with custom address.

...

truffle-plugin-verify 0.5.20
Truffle v5.4.25 (core: 5.4.25)
Solidity - 0.8.10 (solc-js)
Node v17.2.0
Web3.js v1.5.3

...

> truffle run verify TPVTest@0xE440D0a016816AbA5a792BD97f03a2dA195B712a  --network polygon_testnet --debug

Console Output:

DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.20
Retrieving network's chain ID
Verifying TPVTest@0xE440D0a016816AbA5a792BD97f03a2dA195B712a
Reading artifact file at /TPVTest/build/contracts/TPVTest.json
Custom address 0xE440D0a016816AbA5a792BD97f03a2dA195B712a specified
Failed to verify 1 contract(s): TPVTest@0xE440D0a016816AbA5a792BD97f03a2dA195B712a

**Comment by rkalis** [comment]
Can you look at #97 and see if that matches what you're experiencing and if using the `legacy` tag works for you? And could you provide a repository where this issue can be reproduced?

**Comment by shep-analytics** [comment]
Hi, I still have the same problem, and legacy doesn't seem to work.

**Comment by rkalis** [comment]
Do you have a repository?

**Comment by shep-analytics** [comment]
> Do you have a repository?

https://github.com/shep-analytics/widget

**Comment by rkalis** [comment]
Thanks for the repo @shep-analytics. I was able to track down the issue, will include the fix in the next release (some time next week).

**Comment by 17y** [comment]
> 

Same issue. Please let me know if fixed.

**Comment by BunHouth** [comment]
I unable to verify contract using latest version.  But using version `0.5.15` save my life.

`"truffle-plugin-verify": "0.5.15"`
