### ISSUE TITLE
JavaScript heap out of memory when verifying contracts with circular dependencies

### ISSUE THREAD

**Issue by JohannesMayerConda** [rkalis/truffle-plugin-verify#14]
I get the following error:

<--- Last few GCs --->

[38003:0x102804000]   172720 ms: Scavenge 1214.8 (1437.4) -> 1199.8 (1438.4) MB, 3.3 / 0.0 ms  (average mu = 0.282, current mu = 0.184) allocation failure 
[38003:0x102804000]   173260 ms: Mark-sweep 1215.2 (1438.4) -> 1196.5 (1436.4) MB, 516.1 / 0.0 ms  (average mu = 0.387, current mu = 0.474) allocation failure scavenge might not succeed
[38003:0x102804000]   173326 ms: Scavenge 1212.1 (1436.4) -> 1197.0 (1437.9) MB, 3.5 / 0.0 ms  (average mu = 0.387, current mu = 0.474) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x20779e1dbe3d]
    1: StubFrame [pc: 0x20779e1dd3c6]
Security context: 0x167c9529e6e9 <JSObject>
    2: /* anonymous */ [0x167c603a2509] [/Users/USER/FOLDER/github/TOKEN/node_modules/sol-merger/dist/lib/fileAnalyzer.js:~38] [pc=0x20779e668601](this=0x167c603a24e9 <FileAnalyzer map = 0x167caacd7869>)
    3: next [0x167c95299de9](this=0x167c603a2841 <JSGenerator>,0x167c603babc1 <Very long string[3528]>)
    4: fulfi...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003d035 node::Abort() [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 2: 0x10003d23f node::OnFatalError(char const*, char const*) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 3: 0x1001b8e15 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 4: 0x100586d72 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 5: 0x100589845 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 6: 0x1005856ef v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 7: 0x1005838c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 8: 0x10059015c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
 9: 0x1005901df v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
10: 0x10055fb24 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
11: 0x1007e7e04 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/USER/.nvm/versions/node/v10.16.3/bin/node]
12: 0x20779e1dbe3d 
Abort trap: 6

**Comment by JohannesMayerConda** [comment]
Update: I then used my custom truffle-flattener and it told me that there is a circular dependency. I could exchange the used contract with a simple ERC20 interface and the error disappeared for my custom truffle-flattener. Now it says "Fail - Unable to verify"

**Comment by JohannesMayerConda** [comment]
Update: I could verify with my custom truffle-flattener but not with truffle-plugin-verify. The reason could be the ctor arguments. I had to generate and paste the bytecode on the etherscan website.

**Comment by ferittuncer** [comment]
I experienced the same. My source code has circular dependency too, perhaps that's why.

**Comment by rkalis** [comment]
Hey guys, do you have an example repository or something I can use to reproduce these issues?

**Comment by nklipa13** [comment]
Just run into same problem and made simple example code that you can test:

Test.sol
```
pragma solidity >=0.4.21 <0.6.0;

import "./Test2.sol";

contract Test {
  address public owner;
  
  constructor() public {
    owner = msg.sender;
  }
}
```

Test2.sol
```
pragma solidity >=0.4.21 <0.6.0;

import "./Test.sol";

contract Test2 {
  address public owner;
  
  constructor() public {
    owner = msg.sender;
  }
}
```

So just two files importing each other and it fails for some reason, probably what @JohannesMayerConda mentioned with ctor arguments.

**Comment by rkalis** [comment]
I looked into this a bit more, but it looks to be an issue with [sol-merger](https://github.com/RyuuGan/sol-merger), so I went ahead and opened an [issue](https://github.com/RyuuGan/sol-merger/issues/27) on that repo. Feel free to join the conversation to add more comments over there.

**Comment by RyuuGan** [comment]
@rkalis, version 2 is released, should be fixed in `sol-merger`

**Comment by rkalis** [comment]
Thanks to @RyuuGan's great work on `sol-merger` support for circular dependencies is now live in v0.3.9.
