### ISSUE TITLE
Failed to verify. No description.

### ISSUE THREAD

**Issue by nacho-villanueva** [rkalis/truffle-plugin-verify#141]
Hello!
I'm trying to verify a contract on PolygonScan for the Mumbai testnet, but I'm getting a failed to verify contract, but I don't get much of a description when using debug. Any idea why? Here's the console result

```
> truffle run verify InfluencerTest@0xC27f0dBCdB35B8C88D7674902D9cb63d63814d8F --debug --network mumbai
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.20
Retrieving network's chain ID
Verifying InfluencerTest@0xC27f0dBCdB35B8C88D7674902D9cb63d63814d8F
Reading artifact file at D:\Code\Solidity\InfluencerTest\build\polygon-contracts\InfluencerTest.json
Custom address 0xC27f0dBCdB35B8C88D7674902D9cb63d63814d8F specified
Failed to verify 1 contract(s): InfluencerTest@0xC27f0dBCdB35B8C88D7674902D9cb63d63814d8F
```

Tried using with and without the @ and nothing changes.
Thank you in advance!

**Comment by nacho-villanueva** [comment]
I believe this isn't a problem with the truffle-verify-plugin, because while using hardhat I get also get an error. My best guess is that there's something wrong with the PolygonScan API for the Mumbai testnet.

**Comment by rkalis** [comment]
Yeah I've been getting a lot of reports about Mumbai not working lately (see #97, #129, #139). So I'll close this issue as a duplicate for now. Not sure if there's much I can do here actually.
