### ISSUE TITLE
Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by denizsurmeli** [rkalis/truffle-plugin-verify#142]
**Describe the bug**

Hey, thanks for your work in advance. I have tested and migrated my contracts using truffle, contracts are deployed on `rinkeby` but I get the error `Cannot read property 'address' of undefined`. You can check the repo that I'm working on in [here](www.github.com/denizsurmeli/interface). I must also note that one of the contracts depend on other contract's address, but I assume that `truffle migrate --network rinkeby` handles it. 

**Steps To Reproduce**
I open up a terminal in my repo, tried both as `sudo` and regular user, run command:
`truffle run verify LegalEntityVerification Provenance --network rinkeby`
and error occurs.
**Environment information**

Please provide environment information as complete as possible. Before submitting a bug report, please make sure that you're running an LTS version of Node and the latest versions of Truffle and truffle-plugin-verify.

- Operating System: (macOS 12.1)
- Node version: (v14.18.0)
- Truffle version: (v5.4.26)
- truffle-plugin-verify version: (v0.5.20)

**Debug output**
```
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.20
Retrieving network's chain ID
Verifying LegalEntityVerification
Reading artifact file at /Users/denizsurmeli/Desktop/interface/client/src/contracts/LegalEntityVerification.json
Cannot read property 'address' of undefined
Verifying Provenance
Reading artifact file at /Users/denizsurmeli/Desktop/interface/client/src/contracts/Provenance.json
Cannot read property 'address' of undefined
Failed to verify 2 contract(s): LegalEntityVerification, Provenance
```

**Comment by denizsurmeli** [comment]
Sorry about the link to the repo, here is the absolute path: www.github.com/denizsurmeli/interface

**Comment by rkalis** [comment]
Hi Deniz, is it possible that you didn't deploy any contracts yet. It looks like this error could occur if that is the case. I will update the error message in any case.

If you are sure that you did deploy the contracts (with `truffle migrate ...`), I'll have to look into it more.

**Comment by denizsurmeli** [comment]
Hi Rosco, I can see the contracts on etherscan, I have deployed them on Rinkeby. I have forced to migrate again with `truffle migrate --network rinkeby --reset`. I have also checked the json outputs in src/contracts, and the address seen there is also the current deployed address. Is is possible that plugin do not work because I use the truffle-react box ?

**Comment by denizsurmeli** [comment]
Hey Rosco, no problems on the repo end. As you know, you can bypass network id in your `truffle-config.js` file by passing `network_id:"*"`. After I have looked up the source code a bit, I found my mistake . Thanks for your help, sorry for wasting your time. Sincerely.

**Comment by rkalis** [comment]
Oh I see. That's an interesting edge case. With three update I made yesterday it should at least provide a better error message in this case.
