### ISSUE TITLE
Verification not working at all on testnets (Rinkeby, BSC, Mumbai)

### ISSUE THREAD

**Issue by AbdulHannanButt** [rkalis/truffle-plugin-verify#143]
**Description**

While verifying smart contract through plugin it just stuck infinitely at verifying 

**Steps To Reproduce**

Write any simple smart contract with any solidity version and try to verify it using plugin will get stuck. In my case the contract was of single function returning msg.sender

**Environment Information**:

- Operating System: ubuntu 20.04
- Node version: 14.18.3
- Truffle version: 0.5.0 / 0.8.0 (checked on both)
- truffle-plugin-verify version: 0.5.15 / 0.5.20 (checked on both)

**Debug report**:

DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.16
Verifying Hello
Reading artifact file at /home/abdul/Desktop/NFTRuffian/build/contracts/Hello.json
Retrieving constructor parameters from https://api-testnet.polygonscan.com/api?apiKey=&module=account&action=txlist&address=0x895CbD3b1a09D02Cf2d8652e8c888bb91BBACA00&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x
Sending verify request with POST arguments:
{
  "apikey": "",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0x895CbD3b1a09D02Cf2d8652e8c888bb91BBACA00",
  "sourceCode": "{\"language\":\"Solidity\",\"sources\":{\"/contracts/Hello.sol\":{\"content\":\"pragma solidity ^0.8.1;\\ncontract Hello{\\n    constructor(){}\\n    function test() public view returns(address){\\n        return msg.sender;\\n    }\\n}\"}},\"settings\":{\"remappings\":[],\"optimizer\":{\"enabled\":true,\"runs\":200},\"evmVersion\":\"istanbul\",\"libraries\":{}}}",
  "codeformat": "solidity-standard-json-input",
  "contractname": "/contracts/Hello.sol:Hello",
  "compilerversion": "v0.8.1+commit.df193b15",
  "constructorArguements": ""
}
Checking status of verification request zyjtr679jbadzqp2j3gup61ey82vzaapcpv15qzjf9agxhkba5

Stuck at this infinitely

**Comment by gankerjack** [comment]
Same issue here, takes a really long time and then eventually fails. Then tried it with a very simple contract - same thing. Was able to verify manually on etherscan.

**Comment by kanedaaaa** [comment]
Doesn't work on mainnets either, trying to verify the contract (that I verified previously) on polygon but it is stuck on `Verifying Contractname`.

I will try with older version.

**Comment by cryptoturk** [comment]
Same issue here, takes a long time and fails

**Comment by nodezy** [comment]
Please fix sirs, for my village

**Comment by 0xV4L3NT1N3** [comment]
gm all, we did experience some issues with the contract verification APIs earlier today, causing truffle's verify plugin to fail.

We've since caught up with the backlog of verifications, everything should be back on the beat now. 

Tested it to be working on `truffle-plugin-verify v0.5.18` , feel free to ping us here if anyone's issues still persist!

**Comment by AbdulHannanButt** [comment]
Just tested it and its working now. Thanks for fixing this

**Comment by Agilulfo1820** [comment]
Still having this issue

**Comment by nodezy** [comment]
> Still having this issue

Can confirm, hangs again on verify. Looks like I'm gonna have to flatten my contracts again :/

**Comment by nodezy** [comment]
Seems to be working again as of today
