### ISSUE TITLE
extra linebreaks are inserted randomly in verified code

### ISSUE THREAD

**Issue by prestwich** [rkalis/truffle-plugin-verify#15]
Verified code is [here](https://ropsten.etherscan.io/address/0xBA0BD26775477b077741fDbB67BEDA38B19385A9#code)

Many extra line breaks are inserted throughout the verified code. Particularly between logical blocks

**Comment by rkalis** [comment]
Hmm yeah that's odd indeed. I'm thinking this might have something to do with [sol-merger](https://github.com/RyuuGan/sol-merger), which is the dependency that truffle-plugin-verify uses to flatten contract code. Any thoughts, @RyuuGan?

**Comment by RyuuGan** [comment]
@rkalis, @prestwich  They are not randomly. Before there were comments, but since `1.0.0` comments are removed but instead empty lines are in their place.

**Comment by rkalis** [comment]
Ah that explains it. Is the deletion of comments intentional? If so, what's the rationale behind it?

**Comment by prestwich** [comment]
why delete the text but leave the linebreak?

**Comment by RyuuGan** [comment]
@rkalis Deletion of comments was intentional, because I didn't want to write parser for comments.

@prestwich I use library that deletes comments, and it behaves likes like this. It removes only comments but blank lines with the spaces are left.

**Comment by rkalis** [comment]
@RyuuGan added functionality to preserve comments in flattened code, which I enabled in `truffle-plugin-verify@0.3.8`.  When using this version, all comments are preserved, and no random line breaks are inserted.
