### ISSUE TITLE
Truffle dashboard compatibility with truffle-plugin-verify

### ISSUE THREAD

**Issue by sharp2448** [rkalis/truffle-plugin-verify#156]
Hi there,
First let me tell you that I'm big fan of this plugin! 

So I just tried **truffle-plugin-verify** with **Truffle Dashboard**(recent Truffle feature), but I got `network_id bypassed with "*" in truffle-config.js.`
Even though I tried hard coding or commenting out any network_id variable.

Not sure if it's bug on my side, but I'm guessing that **truffle-plugin-verify** is not updated to work with recent Truffle Dashboard feature, right?

If the bug is on my side and for you **truffle-plugin-verify** work fine with **Truffle Dashboard** feel free to delete this post and I will try to fix my bug.

**Comment by rkalis** [comment]
Good catch! This is something that I realised earlier as well, but haven't implemented a fix for yet.

If you had to choose, which would be your preferred of these two options?

1. You have to have your Truffle Dashboard running while you're running `truffle run verify ...`
2. You have to manually specify the network ID you want to use

**Comment by rkalis** [comment]
I figured (1) would actually be the way to go. So I just published v0.5.23 of the plugin that works with the Truffle Dashboard as long as you have the dashboard running and connected to the correct network (the same as you used to deploy). Also added a note to the README about that.

Thanks again!

**Comment by sharp2448** [comment]
Wow, fast fix. What a legend! Thank you. 
Btw, I agree option 1 make more sense.
