### ISSUE TITLE
Support for specifying custom api urls

### ISSUE THREAD

**Issue by Mukundan314** [rkalis/truffle-plugin-verify#168]
The ability to provide custom API urls will allow verifying of contracts on private BlockScout (which provides a Etherscan compatible API under `/api`) instances.

configuration format I'm thinking of:
```js
// truffle-config.js

module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*",
            verify: {
                apiUrl: "http://localhost:4000/api"
            }
        },
        ...otherNetworks,
    },
   ...restOfTruffleConfig,
}
```

---

Would be happy to make a PR for this

**Comment by rkalis** [comment]
This is a great idea! Would love to take a PR for this.

**Comment by Mukundan314** [comment]
@rkalis Made a PR for this: https://github.com/rkalis/truffle-plugin-verify/pull/169
