### ISSUE TITLE
Feature Request: Circular Dependency

### ISSUE THREAD

**Issue by ferittuncer** [rkalis/truffle-plugin-verify#17]
Please support source codes with circular dependency.

**Comment by gorgos** [comment]
Currently results in an infinite loop AFAICS.

**Comment by rkalis** [comment]
I looked into this a bit more, but it looks to be an issue with [sol-merger](https://github.com/RyuuGan/sol-merger), so I went ahead and opened an [issue](https://github.com/RyuuGan/sol-merger/issues/27) on that repo. Feel free to join the conversation to add more comments over there.

**Comment by rkalis** [comment]
I'm going to close this issue by the way and consolidate it with #14.
