### ISSUE TITLE
Not able to verify on BSC Testnet, hangs

### ISSUE THREAD

**Issue by nodezy** [rkalis/truffle-plugin-verify#174]
**Describe the bug**

Cannot verify contract on BSC testnet

**Steps To Reproduce**

1. Migrate contract to BSC Testnet
2. Run truffle run verify contract@address and it will hang without completing or verifying

**Environment information**

- Operating System: Windows 11
- Node version: v14.15.4.
- Truffle version: v5.5.16
- truffle-plugin-verify version: v0.5.26

**Debug information**

Checking status of verification request tc4m4i9uezsrd1jwaar6st3amwsfaeuwjecd1nxyjtfyf52wkj

**Comment by nodezy** [comment]
aaaand now its working again...

**Comment by rkalis** [comment]
Sometimes the bscscan API can have some temporary issues, which is likely what was happening here.
