### ISSUE TITLE
Unable to verify since 0.8.16

### ISSUE THREAD

**Issue by MaxflowO2** [rkalis/truffle-plugin-verify#180]
**Describe the bug**

Since Solc 0.8.16 have had issues verifying contracts on testnet.

**Steps To Reproduce**

**Environment information**
Truffle v5.5.25 (core: 5.5.25)
Ganache v7.4.0
Solidity - 0.8.17 (solc-js)
Node v16.17.0
Web3.js v1.7.4
truffle-plugin-verify 0.5.28

**Debug output**
Running truffle-plugin-verify v0.5.28
Retrieving network's network ID & chain ID
Verifying RoyaltySplitter
Reading artifact file at /solidity-dev/am-gothic/build/contracts/RoyaltySplitter.json
Retrieving constructor parameters from https://api-rinkeby.etherscan.io/api?apiKey=&module=account&action=txlist&address=0x8632fbD3f2D5d7115c56FecEb90E98b0272FF528&page=1&sort=asc&offset=1
Constructor parameters retrieved: 0x
Sending verify request with POST arguments:
{
  "apikey": ",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0x8632fbD3f2D5d7115c56FecEb90E98b0272FF528",
  "sourceCode": "...the source...",
  "codeformat": "solidity-standard-json-input",
  "contractname": "/contracts/royalties.sol:RoyaltySplitter",
  "compilerversion": "v0.8.17+commit.8df45f5f",
  "constructorArguements": ""
}
Checking status of verification request stepd1jsklg2darsck7ea8aykexgwdi2t7thjqygaxssg55ypg
Fail - Unable to verify
Failed to verify 1 contract(s): RoyaltySplitter

**Comment by rkalis** [comment]
Could you provide a minimal repo where I can reproduce this issue?

**Comment by MaxflowO2** [comment]
fixed this with -d instead of -g on npm
