### ISSUE TITLE
verifying smart contract fails when using viaIR is true in truffle config

### ISSUE THREAD

**Issue by payamsafaei** [rkalis/truffle-plugin-verify#181]
**Describe the bug**

verifying smart contract fails when  viaIR is true in truffle config

**Steps To Reproduce**
verifying smart contract fails when viaIR is true in truffle config

```
compilers: {
     solc: {
       version: "0.8.16",    // Fetch exact version from solc-bin (default: truffle's version)
       //docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
       settings: {          // See the solidity docs for advice about optimization and evmVersion
         optimizer: {
           enabled: true,
           runs:200
         },
         evmVersion: "london",
           viaIR: true
       }
     }
```

https://github.com/rkalis/truffle-plugin-verify/
**Environment information**

Please provide environment information as complete as possible. Before submitting a bug report, please make sure that you're running an LTS version of Node and the latest versions of Truffle and truffle-plugin-verify.

- Operating System: win11
- Node version: v16.15.1
- Truffle version:  v5.5.28
- truffle-plugin-verify version: v0.5.28

**Debug output**

Fail - Unable to verify
Failed to verify 1 contract(s): NFTGame

**Comment by rkalis** [comment]
Hmm interesting. Could you provide a minimal repo where I can reproduce this issue?

**Comment by ekn1012** [comment]
is your evm version correct? isn't byzantium the default for viaIR?

**Comment by heisendevs** [comment]
Hi all, I modified these lines and was able to verify the contract

File: node_modules/truffle-plugin-verify/verify.js

  const inputJSON = {
    language: metadata.language,
    sources,
    settings: {
      remappings: metadata.settings.remappings,
      **metadata: metadata.settings.metadata,**
      **viaIR: true,**
      optimizer: metadata.settings.optimizer,
      evmVersion: metadata.settings.evmVersion,
      libraries
    }
  }

**Comment by kazunetakeda25** [comment]
Hi @heisendevs where do you see inputJSON variable defined? I can't see it

**Comment by ivalenzuela** [comment]
> Hi @heisendevs where do you see inputJSON variable defined? I can't see it

Maybe you are in a new version, try looking at node_modules/truffle-plugin-verify/dist/types.d.ts

**Comment by kazunetakeda25** [comment]
> Hi all, I modified these lines and was able to verify the contract
> 
> File: node_modules/truffle-plugin-verify/verify.js
> 
> ```
>   const inputJSON = {
>     language: metadata.language,
>     sources,
>     settings: {
>       remappings: metadata.settings.remappings,
>       metadata: metadata.settings.metadata,
>       viaIR: true,
>       optimizer: metadata.settings.optimizer,
>       evmVersion: metadata.settings.evmVersion,
>       libraries
>     }
>   }
> ```

I tried this, but didn't work. (I tried with 0.6.0 and 0.6.1 versions)

**Comment by sebastian-baier** [comment]
I have the same problem with version 5.32.
I added 
'viaIR: true'
to inputJSON in verify to fix it

**Comment by rkalis** [comment]
Truffle is being sunset, so I expect people to move away from Truffle and therefore truffle-plugin-verify. When I tried in the past I haven't been able to figure out a generalised fix that works both with and without `viaIR`. So with those things in mind I think the workaround mentioned in this thread is *good enough* and I'll close this issue.
