### ISSUE TITLE
Etherscan has no support for network arbitrum_goerli with chain id 421613

### ISSUE THREAD

**Issue by coin77** [rkalis/truffle-plugin-verify#182]
Would it be possible to add Aribtrum Goerli, chain id 421613 to the verify plugin? Rinkeby and Arbitrum Rinkeby are deprecated. Thanks!

**Comment by rkalis** [comment]
This was just added by @d10r, published in the new version 0.5.29

**Comment by coin77** [comment]
Yes, it works with the latest version. Thank you very much!
