### ISSUE TITLE
support for sepolia

### ISSUE THREAD

**Issue by Applecakeman** [rkalis/truffle-plugin-verify#185]
Hello,

I just tried to verify my contract on the sepolia testnet.
I'm getting this error message: Etherscan has no support for network sepolia with chain id 11155111

Thanks

**Comment by Applecakeman** [comment]
you just need to add this two lines in constants.js
`11155111: 'https://api-sepolia.etherscan.io/api',`
`11155111: 'https://sepolia.etherscan.io/address',`

just tested it
works for me

Thank you
hope it will be integregrated

**Comment by rkalis** [comment]
Thans for the PR! Closing this issue.
