### ISSUE TITLE
TypeError: (intermediate value).hostname.split(...).at is not a function

### ISSUE THREAD

**Issue by BarneyChambers** [rkalis/truffle-plugin-verify#189]
**Describe the bug**

When I run `truffle run verify <contractAddress> --network polygon` I receive the following error: 

`TypeError: (intermediate value).hostname.split(...).at is not a function`

**Environment information**

Please provide environment information as complete as possible. Before submitting a bug report, please make sure that you're running an LTS version of Node and the latest versions of Truffle and truffle-plugin-verify.

- Operating System: (WSL)
- Node version: 15.14.0
- truffle-plugin-verify version: "truffle-plugin-verify": "^0.6.0"

**Debug output**
```
DEBUG logging is turned ON
Running truffle-plugin-verify v0.6.0
Retrieving network's network ID & chain ID
TypeError: (intermediate value).hostname.split(...).at is not a function
    at getPlatform (/mnt/c/Users/Barne/Desktop/minima/Minima-ICO/node_modules/truffle-plugin-verify/dist/util.js:137:58)
    at getApiKey (/mnt/c/Users/Barne/Desktop/minima/Minima-ICO/node_modules/truffle-plugin-verify/dist/util.js:153:63)
    at /mnt/c/Users/Barne/Desktop/minima/Minima-ICO/node_modules/truffle-plugin-verify/dist/verify.js:59:41
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/c/Users/Barne/Desktop/minima/Minima-ICO/node_modules/truffle-plugin-verify/dist/verify.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Truffle v5.5.17 (core: 5.5.17)
Node v15.14.0```

**Comment by BarneyChambers** [comment]
Seems to work after going into `util.js` and changing some code like so

```
    const platform = "";
    const subPlatform = "polygonscan";
    //const platform = new URL(apiUrl).hostname.split('.').at(-2);
    //let subPlatform = (_a = new URL(apiUrl).hostname.split('.').at(-3)) === null || _a === void 0 ? void 0 : _a.split('-').at(-1);
    // For some reason Etherscan uses both optimistic.etherscan.io and optimism.etherscan.io
    //if (subPlatform === 'optimism')
    //    subPlatform = 'optimistic';
```

**Comment by rkalis** [comment]
Thanks for the report! I'll look into this. Could you share your truffle-config file as well?

**Comment by BarneyChambers** [comment]
const HDWalletProvider = require('@truffle/hdwallet-provider');
const mnemonic = '<MNEMONIC>';

module.exports = {
  networks: {
    polygon: {
      provider: () => new HDWalletProvider(mnemonic, `https://polygon-rpc.com`),
      network_id: 137,
      chainId: 137,
      from: "0x8C185e652F60ff828134402D8B65D4508a9baA4d",
      gasPrice: 50000000000, //50 gwei
    }, 
  },
  compilers: {
    solc: {
      version: "0.8.12",    // Fetch exact version from solc-bin (default: truffle's version)
      settings: {          // See the solidity docs for advice about optimization and evmVersion
        optimizer: {
          enabled: true,
          runs: 9999
        },
        evmVersion: "byzantium"
      }
    }
  },
  plugins: [
    'truffle-plugin-verify'
  ],
  api_keys: {
    polygon: '<KEY>'
  }
};

**Comment by rkalis** [comment]
Hey! This was an issue with `Array.prototype.at` not being supported by Node 15. I just pushed v0.6.1 of the plugin that should work with your version of Node.
