### ISSUE TITLE
Support EVM version target

### ISSUE THREAD

**Issue by rkalis** [rkalis/truffle-plugin-verify#20]
Truffle allows you to specify an EVM version in the compiler settings. Etherscan allows you to specify this EVM version as well in the verify wizard on their website. However, there's no option for this in the Etherscan verify API, making it impossible for `truffle-plugin-verify` to support these EVM version targets.

If this is added to the Etherscan API support can be added to the plugin.

**Comment by rkalis** [comment]
@mtbitcoin @kvrnc is this something that could be added to the verify API on your side?

**Comment by mtbitcoin** [comment]
Sure, will add this into our issue tracker

**Comment by rkalis** [comment]
This feature has been added to the Etherscan API, so I updated `truffle-plugin-verify@0.3.5` to include an automatic inference of the `evmTarget` settings in the `truffle-config.js` file.
