### ISSUE TITLE
Cannot read properties of undefined (reading "address") during verification

### ISSUE THREAD

**Issue by samyan** [rkalis/truffle-plugin-verify#205]
Hi,

The current version **0.6.4** seems to have a bug. Just for test I tried with **0.5.33** and my contract was verified successfully.

**Steps To Reproduce**

Install the version **0.6.4**

`truffle run verify TetherUSD@0xbc5ac34A5Ef927Cd0AecaBC402feAf1a013BA459 --network sepolia --verifiers=etherscan --debug `

**Environment information**

- Operating System: Windows 11
- Truffle v5.7.4 (core: 5.7.4)
- Ganache v7.7.3
- Solidity - 0.8.19 (solc-js)
- Node v16.15.1
- Web3.js v1.8.1

- truffle-plugin-verify version: 0.6.4

**Truffle Config**

```javascript

const HDWalletProvider = require('@truffle/hdwallet-provider');
const mnemonic = 'MY_MNEMONIC';

module.exports = {
	networks: {
		development: {
			host: 'localhost',
			port: 8545,
			network_id: '*', // Match any network id
			gas: 5000000,
		},
    sepolia: {
      provider: () => {
        return new HDWalletProvider(mnemonic, 'https://sepolia.infura.io/v3/MY_INFURA_KEY');
      },
      network_id: 11155111,
      gas: 4000000,
    }
	},
	compilers: {
		solc: {
			version: '0.8.19',
			settings: {
				optimizer: {
					enabled: false,
					runs: 200,
				},
			},
		},
	},
	plugins: ['truffle-contract-size', 'truffle-plugin-verify'],
	api_keys: {
		etherscan: 'MY_API_KEY',
	},
};
```

**Console**

```
DEBUG logging is turned ON
Running truffle-plugin-verify v0.6.4
Retrieving network's network ID & chain ID
Verifying contracts on etherscan
   Verifying TetherUSD@0xbc5ac34A5Ef927Cd0AecaBC402feAf1a013BA459
   Resolving artifact for contract TetherUSD
   Cannot read properties of undefined (reading 'address')
   Failed to verify 1 contract(s): TetherUSD@0xbc5ac34A5Ef927Cd0AecaBC402feAf1a013BA459
```

**Comment by rkalis** [comment]
Hey, do you have a minimal repo or steps that I can use to reproduce the issue?

**Comment by samyan** [comment]
> Hey, do you have a minimal repo or steps that I can use to reproduce the issue?

Hi. [Here](https://github.com/samyan/truffle-plugin-verify-bug) the example. As additional and perhaps important information, there is more than one contract created with my wallet that has the same contract name that I try to verify.

**Comment by hilmanshini** [comment]
same thing happened to me, what 'address' is this?

**Comment by samyan** [comment]
Hello. The problem appears when you have 2 contract compiled with the same name.

**Comment by rkalis** [comment]
If that is what causes the problem, could you make sure that the reproduction example contains all the prerequisites for me to reproduce the issue (i.e. the duplicate named contracts). If that is what is causing the issue though, then I assume that @cds-amal is correct and the solution would be to *not* have two contracts with the same name in the same project.

**Comment by samyan** [comment]
> If that is what causes the problem, could you make sure that the reproduction example contains all the prerequisites for me to reproduce the issue (i.e. the duplicate named contracts). If that is what is causing the issue though, then I assume that @cds-amal is correct and the solution would be to *not* have two contracts with the same name in the same project.

If you read the previous comments you will realize that I mention the possible error of contract name later because when I opened the thread, I had not realized it.  Anyways, you can close the thread if you want.
