### ISSUE TITLE
Not working for Kovan

### ISSUE THREAD

**Issue by nklipa13** [rkalis/truffle-plugin-verify#22]
It seems that the verifier isn't working for the last two days. 

Steps to reproduce:
Create new repo, follow all instructions from readme file with some simple test contract and try to verify on Kovan test network, haven't checked for other networks, 

for Kovan it says "Unable to verify", 
for Mainnet says "No instance of contract Test found for network id 1"

**Comment by rkalis** [comment]
Hey, thanks for opening this issue. I tried to do a test with a SimpleStorage instance on Rinkeby, and I got the same results. I outputted the data I sent to the Etherscan API:

```js
{ apikey: <redacted>,
  module: 'contract',
  action: 'verifysourcecode',
  contractaddress: '0x818887C7AE9057FBa6380EcE5f8034b3B85D197a',
  sourceCode:
   'pragma solidity ^0.5.0;\n\n\ncontract SimpleStorage {\n  uint storedData;\n\n  function set(uint x) public {\n    storedData = x;\n  }\n\n  function get() public view returns (uint) {\n    return storedData;\n  }\n}',
  codeformat: 'solidity-single-file',
  contractname: 'SimpleStorage',
  compilerversion: 'v0.5.8+commit.23d335f2',
  optimizationUsed: 0,
  runs: 200,
  constructorArguements: '',
  evmversion: undefined,
  licenseType: 1 }
```

I tried copy-pasting these values into the [Etherscan verify web form](https://rinkeby.etherscan.io/verifyContract). This worked correctly. 

So then I tried copy-pasting these values into the [Etherscan verify API demo](https://rinkeby.etherscan.io/sourcecode-demo.html). This did not work.

This leads me to believe that there might be an issue with the Etherscan verify API at the moment, since both truffle-plugin-verify and the API demo did not work, while the web form did work.

@mtbitcoin, are there any known issues with the verify API at this time?

**Comment by mtbitcoin** [comment]
We are looking into this. We did recently push some changes to support submitting standard input json contract verification

**Comment by Enigmatic331** [comment]
Hey @rkalis - Have done a quick test using the same source through the Rinkeby's verify API demo - Seemed to work fine on my end with the contract: https://rinkeby.etherscan.io/address/0xa70e7FB5aad8f9FF2dDec26bbf54dAA026f72FbD#code

Likewise for Kovan: https://kovan.etherscan.io/address/0x7Ff1037803575eE91B13C25A145d68D5Adb6E8A6

A quick screencap on the settings (perhaps some bits of the setting requirements changed in between these couple of days):

![image](https://user-images.githubusercontent.com/28551011/68005686-03857680-fcb1-11e9-85fd-e93904e84c24.png)

I will give it a shot through the Truffle Verify Plugin itself to see if there might be anything I am missing (though I have to admit, I hadn't been using Truffle for a while now).

**Comment by Enigmatic331** [comment]
Hey @rkalis - Fixes were pushed across and a few tests were done (e.g.: https://kovan.etherscan.io/address/0x144f09D87A02719c869cfE407b5e1188a7DB59fa#code)

Any chance for a retry to see if it looks good now, please?
Many thanks!

**Comment by nklipa13** [comment]
@Enigmatic331 it seems that plugin is working properly now

**Comment by rkalis** [comment]
Thanks for the quick fixes @mtbitcoin @Enigmatic331!

**Comment by Julio77** [comment]
Hi @rkalis  ,
I am trying to verify the contracts deployed by truffle, but I get the following:

`x:>truffle run verify Contrato1 Contrato2 --network rinkeby
Truffle v4.1.11 - a development framework for Ethereum

Usage: truffle <command> [options]

Commands:
  init      Initialize new and empty Ethereum project
  compile   Compile contract source files
  migrate   Run migrations to deploy contracts
  deploy    (alias for migrate)
  build     Execute build pipeline (if configuration present)
  test      Run JavaScript and Solidity tests
  debug     Interactively debug any transaction on the blockchain (experimental)
  opcode    Print the compiled opcodes for a given contract
  console   Run a console with contract abstractions and commands available
  develop   Open a console with a local development blockchain
  create    Helper to create new contracts, migrations and tests
  install   Install a package from the Ethereum Package Registry
  publish   Publish a package to the Ethereum Package Registry
  networks  Show addresses for deployed contracts on each network
  watch     Watch filesystem for changes and rebuild the project automatically
  serve     Serve the build directory on localhost and watch for changes
  exec      Execute a JS module within this Truffle environment
  unbox     Download a Truffle Box, a pre-built Truffle project
  version   Show version number and exit

See more at http://truffleframework.com/docs`

**Versions**:
Truffle v4.1.11
TestNet: Rinkeby
Solidity 0.4.24

**Contracts**:
[Contract 1](https://rinkeby.etherscan.io/address/0xa0979526b80811f9e4bfb044450819f06661b23d)
[Contract 2](https://rinkeby.etherscan.io/address/0x0e570b2aec6f060ace9f535b6a8fbddced96501c)

Regards.

**Comment by rkalis** [comment]
Hi @Julio77. Truffle plugins were introduced in Truffle v5.0, so you should update your Truffle installation to use truffle-plugin-verify!

**Comment by Julio77** [comment]
Hi @rkalis 
Thanks, nice, i will try again with this code.
