### ISSUE TITLE
Verifying stuck

### ISSUE THREAD

**Issue by nklipa13** [rkalis/truffle-plugin-verify#26]
I'm having a problem for the last two days (at least) that when I run verifying it just stuck. So it says 

`Verifying Name_of_contract` 

and it stays like that for at least one hour (I stopped after that). I have connection to the internet and my API key is valid (even tried changing it to the new one)

**Comment by rkalis** [comment]
Thanks for the heads up. I'm seeing the same thing. Not sure what's causing this yet, so I'll look into it.

**Comment by rkalis** [comment]
Hey, I wasn't able to figure out the problem last week, but after retrying today it appears to be resolved. Could you check if it is working again for you as well. If it is I think there just might have been an issue with Etherscan's API for a few days.

**Comment by nklipa13** [comment]
Sorry that it took so long, but yes, it seems to be working now.
