### ISSUE TITLE
Verifying contracts with structs in external file

### ISSUE THREAD

**Issue by sobolev-igor** [rkalis/truffle-plugin-verify#28]
Hi there!

I'm facing the issue with source code verification in case when structs are placed in a separate file (it is allowed since 0.6.0 version of Solidity compiler) and then imported where needed. In debug mode, I found out that imported structs are not added in the flattened source code. Thus, the code cannot be compiled on Etherscan side.

**Comment by rkalis** [comment]
Hey @sobolev-igor, that is interesting. @RyuuGan, is this something that could be added to `sol-merger` for Solidity v0.6.0 support?

**Comment by RyuuGan** [comment]
Can you send me an example of the source code, just a small reproduction

**Comment by sobolev-igor** [comment]
Hi! I'm really sorry I haven't answered for so long! 

This is a test repo https://github.com/sobolev-igor/test where you can do 
```npx truffle migrate --network kovan```
then
```npx truffle run verify Test --network kovan --debug```
and see that `Bug` struct is not added to the source code. 

By the way, I think that currently the best way for verification is Standard-Json-Input. In this case, as I understand, you don't have to resolve imports.

**Comment by RyuuGan** [comment]
Can you test that it is working now ? `sol-merger@3.0.0`

I updated the grammar, so it should support structs and enums and also new syntax.

Best regards

**Comment by rkalis** [comment]
I tested this out and confirmed that the source code is merged correctly with the new sol-merger, thanks @RyuuGan!

But now I'm running into a different issue related to Etherscan. If I copy-paste the merged code into the verify web tool, it works, but if I use truffle-plugin-verify or the Etherscan API demo, it doesn't work. So it seems to me like there's a discrepancy between the online tool and the Etherscan API. 

@mtbitcoin, is that something you guys can look into? The reproduction repo is included in @sobolev-igor's comment above. I tested it against the most recent version of `truffle-plugin-verify`, v0.3.11.

**Comment by Enigmatic331** [comment]
Hey @rkalis thanks for tagging us - Cracking on it. Indeed we have implemented support for this a couple weeks back, maybe I've missed something on the API end.

Will report back.

**Comment by Enigmatic331** [comment]
Hey @rkalis - Sorry it took a while this week!

I've managed to get the contract verified via our sourcedemo with a little adjustment - Bringing the ABIEncoderV2 pragma to the top so it comes before the version pragma:

```
pragma experimental ABIEncoderV2;
pragma solidity 0.6.4;


struct Bug {
    uint256 num;
    string str;
}

contract Test {
    function foo() external view returns (Bug memory) {
        return Bug({
            num: 123,
            str: "123"
        });
    }
}
```
Could I trouble you to give it another shot with this change to see if it works out, please? 🙏 

It's one of those small undocumented quirks which I've been wanting to spend some time to look into for a while now - I'll pull up some time for it. In the meantime, making sure the ABIEncoderV2 comes before the version pragma should sort things out.

Sorry for the trouble! And as always thanks for the report.

**Comment by rkalis** [comment]
Hey @Enigmatic331, thanks for the reply. I've confirmed that it works with the ABIEncoderV2 pragma on top. I'll add a note to the README about this for now and consider this issue fixed. Thanks for the great work @RyuuGan and @Enigmatic331!
