### ISSUE TITLE
Contract created through another contract

### ISSUE THREAD

**Issue by ffarhanaamin** [rkalis/truffle-plugin-verify#35]
I am trying to verify a contract which is created through an internal transaction. hence, this call fails

https://api-ropsten.etherscan.io/api?apiKey={apiKey}&module=account&action=txlist&address={dynamicallyCreatedContract}&page=1&sort=asc&offset=1

hence it can't see the trasnaction and it fails

**Comment by rkalis** [comment]
Hey @ffarhanaamin, thanks for opening this issue. This is already covered in issue #8, so I'll close this isse. 

To respond to the issue: there's not a very easy solution yet. I'm considering to add a flag to the CLI to manually provide constructor parameters so it doesn't need to retrieve them from Etherscan. An alternative solution is to potentially use the Truffle Debugger to see if we can trace back the constructor parameters that were used. But for now unfortunately there's no good workaround.
