### ISSUE TITLE
Questions about ABIEncoderV2 for multiple contracts

### ISSUE THREAD

**Issue by kazamio** [rkalis/truffle-plugin-verify#36]
Hi @rkalis 

I'm struggling with Etherscan verification issues on ABIEncoderV2.

I got multiple contracts like this https://github.com/Computable-Finance/CoFiX/blob/master/contracts/CoFiXFactory.sol

```solidity
pragma solidity ^0.6.6;

import './interface/ICoFiXFactory.sol';
import './interface/ICoFiXController.sol';
import './CoFiXPair.sol';

contract CoFiXFactory is ICoFiXFactory {
}
```

And `CoFiXPair.sol` is the only contract which adopts `ABIEncoderV2`.

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later

pragma solidity ^0.6.6;
pragma experimental ABIEncoderV2;

import "./interface/ICoFiXPair.sol";
import "./CoFiXERC20.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "./interface/ICoFiXFactory.sol";
import "./interface/ICoFiXController.sol";
import "./lib/TransferHelper.sol";
import "./lib/ABDKMath64x64.sol";

contract CoFiXPair is ICoFiXPair, CoFiXERC20 {
}
```

I noticed the limitation on README:

> Due to some limitations in the Etherscan verification engine, if you want to use pragma experimental ABIEncoderV2;, this statement should be the first line in your contract file (even above the pragma solidity ^0.6.0; statement).

I also found the flattened source file would only keep one `pragma experimental ABIEncoderV2;` statement before the code, which I think would affect all contracts.

Does it mean I should put `pragma experimental ABIEncoderV2;` statement before each contract if I'm trying to deploy by truffle and verify by this tool?

I have done some experiments and there's a big difference in bytecode if I'm not adding the `pragma experimental ABIEncoderV2;` statement before each contract.

**Comment by rkalis** [comment]
Hey @kazamio! 

In general, yes, if you want to deploy and verify a contract that imports another solidity file that uses ABIEncoderV2, you need to add the pragma to the top of the file with the contract you want to verify as well. 

If you have other contracts that don't import any ABIEncoderV2 solidity files, you don't have to add the statement to the top of those files. Also, you don't need to add it to the top of any files for contracts you *don't* want to verify.

**Comment by kazamio** [comment]
Thanks a lot @rkalis !

Yes, indeed. Just add the ABIEncoderV2 statement before the `Factory.sol` as https://github.com/Computable-Finance/CoFiX/commit/2b475f8adf803eb01c6189995c7d5f4cc9c204d4 and re-deployed. The etherscan verification works now.
