### ISSUE TITLE
Found duplicate SPDX-License-Identifiers in the Solidity code

### ISSUE THREAD

**Issue by uluhonolulu** [rkalis/truffle-plugin-verify#38]
Hi, I'm trying to verify my Solidity file, but it throws an error despite using the new `--license`` parameter:
```
C:\Projects\Galaxias\file-storage>truffle run verify --licence UNLICENSED Files --network rinkeby      
Verifying Files
Found duplicate SPDX-License-Identifiers in the Solidity code, please provide the correct license with 
--license <license identifier>
Failed to verify 1 contract(s): Files
```

I have removed the SPDX comment from the Files.sol file, but it uses an OZ file (which might use others), and that's where it could get it.

My truffle-plugin-verify version is `0.4.0`.

**Comment by rkalis** [comment]
The flag should be `--license` instead of `--licence`. I'd also recommend putting all flags to the right side of `Files`, i.e.:
```
truffle run verify Files --network rinkeby --license UNLICENSED
```

Let me know if that works.

**Comment by uluhonolulu** [comment]
Oops, I'm so ashamed!

Worked perfectly, thanks!
