### ISSUE TITLE
merging not working with ecma6 style imports

### ISSUE THREAD

**Issue by sidhujag** [rkalis/truffle-plugin-verify#4]
Hi There,

These are my contracts, which are a part of the bridge work from Syscoin <-> Ethereum:

https://etherscan.io/address/0x197a2f58c94eff4b2c6ae0922fbc840080f839c2#contracts
https://etherscan.io/address/0x94bb1afd55616daae06c5014d083f506c5a02619#contracts
https://etherscan.io/address/0x35dfdcf5bb289a8bb994e0a4e3554a4dae504483#contracts
https://etherscan.io/address/0xced7ce5c336bb31f35bc5bdc86c651c7136b3825#contracts
https://etherscan.io/address/0xb64f4f0aeb3ec6cd423df3402909fef5963c1fd6#contracts

I was able to verify them via etherescan online single file verify but noticed a **two issues** that I hope we can resolve here and upstream on sol-merger. I will explain how.

The **first issue** I had was that sol-merger is using a regex that does not support ecma6 style imports you can see the fix for the regex here:

https://regex101.com/r/CNPTp4/2

The old regex is here: https://github.com/RyuuGan/sol-merger/blob/master/lib/merger.js#L27

Which only works for standard import '' statements. So the merged code wasn't working and thus not verifiable since the verifier through the API doesn't support import statements on etherscan. The regex is correct from that link as you can see.

The **second issue** I had was that there is not library linking support. You can see here that you are not pushing libraries: https://github.com/rkalis/truffle-plugin-verify/blob/master/verify.js#L42 and my json artifact has the library linked like below:
For example this is the SyscoinSuperblocks.json:
```
...
  "networks": {
    "1": {
      "events": {},
      "links": {
        "SyscoinMessageLibrary": "0x1b081401c98ed6e62b01bc5379d52abee85ae1e9"
      },
      "address": "0xced7ce5c336bb31f35bc5bdc86c651c7136b3825",
      "transactionHash": "0x8374d59e2fc38328b75295b9c4d0e1d0d91bd71f85a8b8d2fb77eb50dff198ce"
    }
  },
...
```

So SyscoinMessageLibrary should be added as a library link. I noticed that the Etherscan single file verification needed me to enter the library link in order for it to finally verify.

From the API example docs on etherscan we can see the example of how to enter the library links (https://etherscan.io/apis#contracts):

``` //Submit Source Code for Verification
    $.ajax({
        type: "POST",                       //Only POST supported  
        url: "//api.etherscan.io/api", //Set to the  correct API url for Other Networks
        data: {
            apikey: $('#apikey').val(),                     //A valid API-Key is required        
            module: 'contract',                             //Do not change
            action: 'verifysourcecode',                     //Do not change
            contractaddress: $('#contractaddress').val(),   //Contract Address starts with 0x...     
            sourceCode: $('#sourceCode').val(),             //Contract Source Code (Flattened if necessary)
            contractname: $('#contractname').val(),         //ContractName
            compilerversion: $('#compilerversion').val(),   // see http://etherscan.io/solcversions for list of support versions
            optimizationUsed: $('#optimizationUsed').val(), //0 = Optimization used, 1 = No Optimization
            runs: 200,                                      //set to 200 as default unless otherwise         
            constructorArguements: $('#constructorArguements').val(),   //if applicable
            libraryname1: $('#libraryname1').val(),         //if applicable, a matching pair with libraryaddress1 required
            libraryaddress1: $('#libraryaddress1').val(),   //if applicable, a matching pair with libraryname1 required
            libraryname2: $('#libraryname2').val(),         //if applicable, matching pair required
            libraryaddress2: $('#libraryaddress2').val(),   //if applicable, matching pair required
            libraryname3: $('#libraryname3').val(),         //if applicable, matching pair required
            libraryaddress3: $('#libraryaddress3').val(),   //if applicable, matching pair required
            libraryname4: $('#libraryname4').val(),         //if applicable, matching pair required
            libraryaddress4: $('#libraryaddress4').val(),   //if applicable, matching pair required
            libraryname5: $('#libraryname5').val(),         //if applicable, matching pair required
            libraryaddress5: $('#libraryaddress5').val(),   //if applicable, matching pair required
            libraryname6: $('#libraryname6').val(),         //if applicable, matching pair required
            libraryaddress6: $('#libraryaddress6').val(),   //if applicable, matching pair required
            libraryname7: $('#libraryname7').val(),         //if applicable, matching pair required
            libraryaddress7: $('#libraryaddress7').val(),   //if applicable, matching pair required
            libraryname8: $('#libraryname8').val(),         //if applicable, matching pair required
            libraryaddress8: $('#libraryaddress8').val(),   //if applicable, matching pair required
            libraryname9: $('#libraryname9').val(),         //if applicable, matching pair required
            libraryaddress9: $('#libraryaddress9').val(),   //if applicable, matching pair required
            libraryname10: $('#libraryname10').val(),       //if applicable, matching pair required
            libraryaddress10: $('#libraryaddress10').val()  //if applicable, matching pair required
        },
        success: function (result) {
            console.log(result);
            if (result.status == "1") {
                //1 = submission success, use the guid returned (result.result) to check the status of your submission.
                // Average time of processing is 30-60 seconds
                document.getElementById("postresult").innerHTML = result.status + ";" + result.message + ";" + result.result;
                // result.result is the GUID receipt for the submission, you can use this guid for checking the verification status
            } else {
                //0 = error
                document.getElementById("postresult").innerHTML = result.status + ";" + result.message + ";" + result.result;
            }
            console.log("status : " + result.status);
            console.log("result : " + result.result);
        },
        error: function (result) {
            console.log("error!");
            document.getElementById("postresult").innerHTML = "Unexpected Error"
        }
    });
```

Doing these two changes should make truffle-plugin-verify work OOTB for most contracts (simple or advanced).

Thanks for your work!

**Comment by rkalis** [comment]
Thanks for opening this issue you are a total rockstar for digging deep and finding out the cause of these issues 💪.

I see you opened a ticket on the sol-merger about the importing as well. Thanks for that. When they are able to figure this out, I will update the dependency and make sure it's available in the next version.

Regarding the library linking, I just added the functionality to detect linked libraries and add them to the verification process. I tested it manually on a MetaCoin + ConvertLib example, which works, but you might want to test it for your own use case as well.

The library linking functionality is included in `v0.2.2`.

**Comment by sidhujag** [comment]
@rkalis awesome thanks man.. yea the problem I didn't see because im a C++ guy is that imports with aliases are hard to static analyze to figure out what to do when merging, he responded to his commit.. till now I think its best if we do standard imports (thats what I did) I removed the ECMA6 import format and just used the simple format and with your library fix it should work now.. cool I'll test it out again!

Thanks man.

**Comment by sidhujag** [comment]
@rkalis Good work my man! It just works OOTB. Verified my contracts on first pass.
