### ISSUE TITLE
Failed to connect to Etherscan API at url https://api-ropsten.etherscan.io/api

### ISSUE THREAD

**Issue by white-black-hong** [rkalis/truffle-plugin-verify#40]
Help me, follow the documentation, but always fail
![image](https://user-images.githubusercontent.com/68105775/96223044-e203c480-0fbf-11eb-9f30-42f2c98c83a5.png)
https://api-ropsten.etherscan.io/api?apiKey=my-api-key&module=account&action=txlist&address=address&page=1&sort=asc&offset=1
switch to my own API-KEYS, and I have the data

**Comment by rkalis** [comment]
Do you have a repository that I can look at to reproduce this issue?

**Comment by white-black-hong** [comment]
![image](https://user-images.githubusercontent.com/68105775/96546498-f22be480-12dc-11eb-961d-1e27570bc605.png)
curl https://api-ropsten.etherscan.io/api, failure.
 Is this my network reason? But I have opened the VPN and succeeded in the browser
![image](https://user-images.githubusercontent.com/68105775/96544861-eee32980-12d9-11eb-8877-ca2c3888753b.png)
I have read other questions. May I ask that the factory deployment contract and Solidity0.6.0 are now supported

**Comment by rkalis** [comment]
Hmm strange that curl times out, but the browser works for you. On my end both curl and browser connections to api-ropsten.etherscan.io/api work. @Enigmatic331 any idea what might be happening here (see also #39)?

**Comment by rkalis** [comment]
> I have read other questions. May I ask that the factory deployment contract and Solidity0.6.0 are now supported
Factory deployed contracts are not supported yet, Solidity v0.6.0 (and all other versions) are supported.

**Comment by rkalis** [comment]
It looks like this error is the same as #39, so I'll close this one to continue the discussion there.
