### ISSUE TITLE
Multi-file verification file order

### ISSUE THREAD

**Issue by rkalis** [rkalis/truffle-plugin-verify#42]
When verifying with multi-file verification, the plugin orders the files alphabetically by file path. A more intuitive orde would be by their appearance in the source code. This was discussed while implementing multi-file verification (see #37).

I proposed an algorithm like this:
```
for node in artifact.ast.nodes:
  if node.nodeType == "ImportDirective":
    add node.absolutePath to ordered list of source paths
    compute the artifact path for this source path
    recursively apply the same algorithm to this artifact's AST
```

But that turned out to be more difficult because of this:
> I tried to do this today, but I ran into some issues in the step "compute the artifact path for this source path", since it's pretty difficult to find out the artifact file(s) corresponding to a Solidity file, since a file can include one or more contracts with different names.

So we'll have to figure out the best way to get the correct ordering.

**Comment by johnnyshankman** [comment]
Bump! I'll add that ordering is great but I would definitely settle for just being able to control which contract goes first. A very common use case is one main contract with ASCII art at the top which imports a multitude of openzeppelin libraries. As long as that one contract is hoisted the top, I'm not particular about the order of the rest.

**Comment by rkalis** [comment]
That's a very good point you raised there @johnnyshankman. Making sure this "root" contract is on top should be *much* easier than figuring out the complete path, so that is something I can add. It makes sense to me that the "root" contract is the one that is being verified. e.g. `truffle run verify MetaCoin` means that `MetaCoin` will be on top. Can you think of any cases where you *wouldn't* want that contract to be on top?

**Comment by rkalis** [comment]
@johnnyshankman I just pushed version `0.5.15` which should now display the "main" contract on top (as I described in the comment above). Thanks for the suggestion. I'll leave this issue open since the rest of the file ordering is still not the way I would prefer.

**Comment by johnnyshankman** [comment]
@rkalis Wonderful!

**Comment by rkalis** [comment]
Since Truffle is being sunset, I don't plan to add new features, so I'm closing this issue. The "main contract on top" has been good enough for the past years any way.

**Comment by johnnyshankman** [comment]
Fair nuff!
