### ISSUE TITLE
contract verification on Binance Smart Chain or other custom chains.

### ISSUE THREAD

**Issue by ninjadev101** [rkalis/truffle-plugin-verify#50]
We know this is a really good tool for our developers but can we do this for all chains? It is the same as Etherscan but I can't make it easily like this plugin. Kindly support this feature.

**Comment by rkalis** [comment]
v0.5.3 of the plugin now supports verification on BscScan thanks to @xzjcool's PR. I'm open to PRs for other block explorers that offer similar functionality as long as it is a clean integration into the existing code.
