### ISSUE TITLE
The reason Failed to connect to Etherscan API at url https://api-rinkeby.etherscan.io/api

### ISSUE THREAD

**Issue by vipkouyu** [rkalis/truffle-plugin-verify#59]
The reason is probably because ethersan.io is blocked in china mainland.

I use my own computer (in China) to call truffle verify, the system prompts: failed to connect to Etherscan API at URL https://api-rinkeby.etherscan.io/api

And then, The same code, I use the U.S. cloud server, success verified.

In china mianland, the access status as follows:
https://etherscan.io/   (404)
https://cn.etherscan.com/ (Can access)
https://rinkeby.etherscan.io/ (404)
https://kovan.etherscan.io/  (404)

**The following things are strange:**

1、https://api-rinkeby.etherscan.io/api?apiKey=CVXXXXXXXXXXXXXXXXXXXXXX3Y&module=account&action=txlist&address=0xb546dda73132E82Edfdb6598C31b3188585b5722&page=1&sort=asc&offset=1

this link can access in china mainland, the "status":"1","message":"OK", but truffle verify failed, maybe the verify code not only access this link.

2、After using VPN,  the chinese coder can access all the ethercan link, but the truffle verify  still failed.

The above is my experience.

**Comment by rkalis** [comment]
Hmm, that is interesting. Thanks for that information @vipkouyu. Not sure yet how to solve this 🤔

**Comment by zmyqucai8** [comment]
After using VPN, the chinese coder can access all the ethercan link, but the truffle verify still failed.
 
I have the same problem

**Comment by rkalis** [comment]
It has been a long time since any activity on this issue, and I'm not sure what to do about this issue, so I will close this as a wontfix, but if people are still having these issues, I'd be happy to take a PR with a fix.

**Comment by bugdoge** [comment]
I have the same problem

**Comment by bugdoge** [comment]
I konw how to fix it.

When you use vpn network, you need to set the axios proxy setting. 

for me, i edit the source code "verify.js",  and insert the code below:

const HttpsProxyAgent = require('https-proxy-agent'); //need to set the dependencies on package.json
const const axiosDefaultConfig = {
    proxy: false,
    httpsAgent: new HttpsProxyAgent('http://127.0.0.1:8080') //use you vpn proxy address
};
const axios = require ('axios').create(axiosDefaultConfig);  //instead of const axios = require('axios')

And it work!




> It has been a long time since any activity on this issue, and I'm not sure what to do about this issue, so I will close this as a wontfix, but if people are still having these issues, I'd be happy to take a PR with a fix.
