### ISSUE TITLE
Cannot find module '@openzeppelin/contracts/GSN/Context.sol'

### ISSUE THREAD

**Issue by vipkouyu** [rkalis/truffle-plugin-verify#60]
truffle solc version : 0.7.0
OS: windows 10

the json file as bollows:
[http://cdn.yiyashuo.com/Context.json](url)

**Comment by rkalis** [comment]
Can you provide some more context / information? Do you have a repository of your project and/or can you share the output when running the command with the `--debug` flag?

**Comment by vipkouyu** [comment]
@rkalis   solved，the reason is my project structure, I create a folder "ETH contract "  in my nodejs web project.
After i moved the [contract/migration/test/config] to the upper level, the problem is soloved.

**Comment by rkalis** [comment]
Alright, happy to hear you were able to fix the issue!
