### ISSUE TITLE
Vulnerability with axios dependency (v0.5.4)

### ISSUE THREAD

**Issue by sjuanati** [rkalis/truffle-plugin-verify#63]
When installing v0.5.4 of truffle-plugin-verify, an `npm audit` shows the following high-risk vulnerability:

- High:                     Server-Side Request Forgery
- Package:              axios
- Patched in:           >=0.21.1
- Dependency of:   truffle-plugin-verify
- Path:                     truffle-plugin-verify > axios
- More info:            https://npmjs.com/advisories/1594

Would it be possible to upgrade the axios dependency in the next release or have a workaround for the current one?

**Comment by rkalis** [comment]
Thanks for the report! Just released v0.5.5 with updated dependencies.
