### ISSUE TITLE
Fail - Unable to verify: solc@0.8.2

### ISSUE THREAD

**Issue by Theo6890** [rkalis/truffle-plugin-verify#65]
I've lost so much time trying to verify with compiled code using solc@0.8.2 but in fact there is a problem with etherscan verification and solc@0.8.2!

So **use solc@0.8.1** for the moment 😉

**Comment by rkalis** [comment]
Looking at the linked issue on the hardhat repo (https://github.com/nomiclabs/hardhat/issues/1308) this issue doesn't occur any more.
