### ISSUE TITLE
No Etherscan API key specified

### ISSUE THREAD

**Issue by Hashflower** [rkalis/truffle-plugin-verify#67]
HI there, I've specified my API key in the truffle config file but I am getting 
`No Etherscan API key specified` at every try. My API works correctly.

Config : 

```
const { etherscanApiKey } = require('./secrets.json');
api_keys: {
      etherscan: etherscanApiKey

    },
 plugins: [
    'truffle-plugin-verify',
  ],
```

I have also tried by entering the API key directly but same result. Any clues ? Thanks!

**Comment by Hashflower** [comment]
Solved, dumb me had placed the api keys inside the network section....

**Comment by rkalis** [comment]
Glad you were able to figure it out!
