### ISSUE TITLE
FTM Testnet Verification Support

### ISSUE THREAD

**Issue by sunburncrypto** [rkalis/truffle-plugin-verify#73]
I suggest having a FTM testnet support would be nice. Right now FTM itself is cheap but in any case i think it would be better if we could use this package for testnet as well

**Comment by rkalis** [comment]
It doesn't look like FtmScan has support for testnet. You should probably contact their support and let them know you want them to support FTM testnet. If they do, I'm happy to add it to the package. Until then, I'm closing the issue.
