### ISSUE TITLE
Could not locate ContractCode for BscScan even though it already exists on the explorer

### ISSUE THREAD

**Issue by jasonnn0210** [rkalis/truffle-plugin-verify#74]
Hi, I am trying to verify my contract, but it says that it is unable to locate ContractCode. However, when going to bscscan to locate it manually, it is there already. Is there something wrong with the way I am doing things? Thank you!

**Comment by rkalis** [comment]
Could you run the verify command using the `--debug` flag and provide the output here?

**Comment by ThiruDevel** [comment]
I am also trying to verify the contract. But still getting error of "Unable to locate ContractCode at Contractaddress"
Using Truffle framework. Compile all files done. But verify is not working in Bsc Mainnet. But Testnet is working fine.

**Comment by Aether-eum** [comment]
I had the same issue, but it turns out that these days bscscan api is very slow to index new deploys. I tried ~4 hours later and it worked.

**Comment by jasonnn0210** [comment]
hi, i tried it after awhile, and it managed to work, thank you!

**Comment by AtomicLemon** [comment]
Hi! Sounds like I'm having the same issue. My contracts deploy and verify on ropsten & bsc testnet perfectly, but not on bsc mainnet.
