### ISSUE TITLE
Simple ERC20PresetMinterPauserUpgradeable contract can't be verified with Truffle

### ISSUE THREAD

**Issue by NeoXtreem** [rkalis/truffle-plugin-verify#77]
**💻 Environment**
Truffle versions from **package.json**:

    "truffle": "^5.3.6",
    "truffle-plugin-verify": "^0.5.8"

**📝Details**
I'm deploying a simple contract to Rinkeby with the following commands:

    npx truffle migrate --reset --network rinkeby
    npx truffle run verify Foo --network rinkeby

I get the following output:

    Verifying Foo
    Fail - Unable to verify
    Failed to verify 1 contract(s): Foo

Contract deployed [here](https://rinkeby.etherscan.io/address/0x8331B849f47B4694d4DB1fA6021e8a1A5CBcA263).

I ensured the **build\contracts**, **cache**, **artifacts** and **.openzeppelin** folders were deleted before the above steps. It seems that a simple contract is unable to be verified using Truffle. Is this a bug, or am I doing something wrong?

**🔢 Code to reproduce**
This is the contract:

    pragma solidity ^0.8.0;

    import "@openzeppelin/contracts-upgradeable/token/ERC20/presets/ERC20PresetMinterPauserUpgradeable.sol";

    contract Foo is ERC20PresetMinterPauserUpgradeable {
        function initialize() initializer public {
            super.initialize("Foo", "FOO");
        }
    }

This is the deploy script:

    const { deployProxy } = require('@openzeppelin/truffle-upgrades');
    const Foo = artifacts.require('Foo');

    module.exports = async function (deployer) {
      await deployProxy(Foo, { deployer });
    };

My compiler settings from **truffle-config.js**:

    solc: {
      version: "^0.8.0",
      settings: {
        optimizer: {
          enabled: false,
          runs: 200
        },
        evmVersion: "byzantium"
      }
    }

**Comment by gabriel-bersouski** [comment]
similar problem here. Anyone ?

**Comment by rkalis** [comment]
Hey! Thanks for the detailed report. Could you also run the command once with the `--debug` flag and post the output (with API key removed)?

**Comment by NeoXtreem** [comment]
OK, crisis averted. I tried again, but this time deleting the **.openzeppelin** folder first, and it worked!

Thanks, and I hope anyone searching for a similar problem finds this simple 'solution'.

**Comment by rkalis** [comment]
Interesting. Hopefully other people with a similar problem will be able to find this issue and follow the same steps. Thanks!
