### ISSUE TITLE
How to support private chain?

### ISSUE THREAD

**Issue by Shirley-Ji** [rkalis/truffle-plugin-verify#78]
Hi guys,

We created a new chain based on Ethereum Geth version, and we want to do contract verification, how to do it wtih this plugin? It seems the function should not work if Only adding the api url.

And do you know if Ethereum open sourced the source code of how to do contract verification?

Thanks,
Shirley

**Comment by rkalis** [comment]
This plugin currently only works specifically for Etherscan (and derived explorers like BscScan), so unless your chain gets its own explorer under the Etherscan umbrella you won't be able to verify it. However, there are open source solutions, such as blockscout and sourcify that can be amended to work with your own chain and offer verification. But it won't work with this plugin, so you'll have to do some more manual work.
