### ISSUE TITLE
Support for Sourcify

### ISSUE THREAD

**Issue by rkalis** [rkalis/truffle-plugin-verify#83]
Sourcify is a repository of verified source code that uses Solidity's builtin metadata hash functionality.

**Comment by d10r** [comment]
I think this would be a great improvement in terms of security.  
Sourcify uses IPFS which comes with implicit integrity checking due to content addressing. That can avoid security issues like this: https://www.paradigm.xyz/2021/11/hiding-in-plain-sight/

**Comment by rkalis** [comment]
This has been released in v0.6.0 of the plugin.
