### ISSUE TITLE
Failed: Invalid API Key

### ISSUE THREAD

**Issue by tomw1808** [rkalis/truffle-plugin-verify#84]
Might be something really stupid I a not seing:
1. Installed latest truffle-plugin-verify
2. Created an API Key on Etherscan (https://etherscan.io/myapikey) 
3. Added the API Key to truffle
4. I can see the API Key in the Debug output when running `truffle run verify MyContract --network mainnet --debug` but receive an error

Here's the console output and some debug output but shortened for readability:

```
+ truffle-plugin-verify@0.5.8
updated 1 package and audited 491 packages in 3.584s

9 packages are looking for funding
  run `npm fund` for details

found 20 vulnerabilities (17 low, 3 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Test> truffle run verify MyContract --network mainnet --debug
DEBUG logging is turned ON
Running truffle-plugin-verify v0.5.8
Verifying MyContract
Reading artifact file at C:\101Projects\MyContract\build\contracts\MyContract.json
Retrieving constructor parameters from https://api.etherscan.io/api?apiKey=W5UA...&module=account&action=txlist&address=0xbEeC90...&page=1&sort=asc&offset=1
Could not retrieve constructor parameters, using empty parameters as fallback
Sending verify request with POST arguments:
{
  "apikey": "W5UA...",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0xbEeC90...",
  "sourceCode": "{\"language\":\"Solidity\",\"sources\":{\"/C/101Projects/[...]",
  "codeformat": "solidity-standard-json-input",
  "contractname": "/C/101Projects/test/contracts/MyContract.sol:MyContract",
  "compilerversion": "v0.8.0+commit.c7dfd78e",
  "constructorArguements": ""
}
Invalid API Key
Failed to verify 1 contract(s): MyContract
```

What am I missing here? I suspect the error is somewhere on my side - any hints would be very helpful. Thank you.

**Comment by rkalis** [comment]
That's weird. It doesn't look like you're doing anything wrong. It could be that there's a temporary issue with Etherscan. Perhaps you can try generating a new API key and seeing if that works, or wait a day and try again.

**Comment by tomw1808** [comment]
It started working again. Didn't change anything. Love it, works really like a charm - great plugin!

**Comment by rkalis** [comment]
Good to hear that fixed it!
