### ISSUE TITLE
Error: Cannot find module 'pify' when running verification

### ISSUE THREAD

**Issue by the-juju** [rkalis/truffle-plugin-verify#86]
Hello @rkalis First of all, thanks for your work!

I'm running into an error when trying to run this command : 
`truffle run verify MyToken@0xSMARTCONTRACTADDRESS --network mainnet`

The error is : Error: Cannot find module 'pify'  😢 

Anyone got the same problem and find the right fix ?

Have a nice day

**Comment by rkalis** [comment]
I have no idea about this, truffle-plugin-verify doesn't depend on 'pify' afaik. Do you have a repo I can look at?

**Comment by the-juju** [comment]
Hello. This is a strange thing. To solve it I had to run on my own `npm install pify`

You can have a look on your side but it's probably something coming from npm...
Repo : [https://github.com/buyzooka/bzoo](https://github.com/buyzooka/bzoo)

**Comment by rkalis** [comment]
Super weird. Might be some other dependency interfering or something 🤔 

Happy it's solved for you though!
